cubiomes-viewer: Add version 2.6.1
ScoopInstaller/Extras pull request #10147
Opened 2022-12-31 05:04 UTC by THEshezzee

Closes #10146

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2022-12-31 05:05 UTC, THEshezzee commented
/verify

2023-01-19 11:45 UTC, HUMORCE commented
> If the application provides only a 32bit download, the architecture field is not required. In all other cases, architecture field is mandatory.
>
> [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md)

2023-01-19 11:47 UTC, HUMORCE requested changes
x64

2023-01-19 17:14 UTC, THEshezzee commented
/verify
> x64

Sorry, resolved https://github.com/ScoopInstaller/Extras/pull/10147/commits/fdc573bbd84a69dea51c3a8fac89e6e9249c1ed0

2023-01-20 18:31 UTC, THEshezzee commented
/verify

2023-01-21 06:44 UTC, HUMORCE commented on bucket/cubiomes-viewer.json
> +    "license": "GPL-3.0",
```suggestion
    "license": "GPL-3.0-or-later",
```

2023-01-21 08:14 UTC, THEshezzee commented
/verify

2023-01-21 09:07 UTC, HUMORCE approved these changes

2023-01-21 09:15 UTC, HUMORCE requested changes
fix

2023-01-21 09:15 UTC, HUMORCE commented on bucket/cubiomes-viewer.json
> +    "checkver": "github",
```suggestion
    "architecture": {
        "64bit": {
            "url": "https://github.com/Cubitect/cubiomes-viewer/releases/download/3.0.0/cubiomes-viewer-3.0.0-w64.exe#/cubiomes-viewer.exe",
            "hash": "8b715b8f153ded3d08d36af3bf04168041eeff79e5b03322e072262236596237"
        }
    },
    "shortcuts": [
        [
            "cubiomes-viewer.exe",
            "Cubiomes Viewer"
        ]
    ],
    "checkver": "github",
```

2023-01-21 09:15 UTC, HUMORCE commented on bucket/cubiomes-viewer.json
> +    }
```suggestion
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/Cubitect/cubiomes-viewer/releases/download/$version/cubiomes-viewer-$version-w64.exe#/cubiomes-viewer.exe"
            }
        }
    }
```

2023-01-21 09:17 UTC, HUMORCE approved these changes

2023-01-21 10:30 UTC, merged