opennbs: Add version 3.10.0
ScoopInstaller/Extras pull request #10197
Opened 2023-01-06 12:57 UTC by THEshezzee

Closes #10196 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2023-01-07 02:08 UTC, aliesbelik commented
/verify

2023-01-07 19:11 UTC, HUMORCE requested changes

2023-01-07 19:11 UTC, HUMORCE commented on bucket/opennbs.json
> +    "homepage": "https://github.com/OpenNBS/OpenNoteBlockStudio",
```suggestion
    "homepage": "https://opennbs.org/",
```

2023-01-07 19:11 UTC, HUMORCE commented on bucket/opennbs.json
> +    "checkver": "github",
```suggestion
    "checkver": {
        "github": "https://github.com/OpenNBS/OpenNoteBlockStudio"
    },
```

2023-01-07 19:11 UTC, HUMORCE commented on bucket/opennbs.json
> +    "bin": "Minecraft Note Block Studio.exe",
```suggestion
```

2023-01-07 19:11 UTC, HUMORCE commented on bucket/opennbs.json
> +}
```suggestion
}

```

2023-01-07 20:10 UTC, THEshezzee reviewed
Done

2023-01-07 20:32 UTC, HUMORCE commented
/verify

2023-01-08 12:56 UTC, davidxuang commented
Maybe [games](https://github.com/Calinou/scoop-games) is a better place, as you can only use this with the game.

2023-01-08 14:28 UTC, HUMORCE approved these changes

2023-01-13 03:47 UTC, merged