popcorn-time: Add version 0.4.9
ScoopInstaller/Extras pull request #10227
Opened 2023-01-12 03:35 UTC by Zliced13

Closes #10160

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2023-01-12 03:36 UTC, Zliced13 commented
/verify

2023-01-19 08:30 UTC, HUMORCE requested changes

2023-01-19 08:30 UTC, HUMORCE commented on bucket/popcorn-time.json
> +    "homepage": "https://github.com/popcorn-official/popcorn-desktop",
```suggestion
    "homepage": "https://popcorntime.app",
```

2023-01-19 08:30 UTC, HUMORCE commented on bucket/popcorn-time.json
> +    "checkver": "github",
```suggestion
    "checkver": {
        "github": "https://github.com/popcorn-official/popcorn-desktop"
    },
```

2023-01-19 13:13 UTC, Zliced13 commented on bucket/popcorn-time.json
> +    "homepage": "https://github.com/popcorn-official/popcorn-desktop",
The website doesn't work.

2023-01-20 17:14 UTC, Zliced13 commented on bucket/popcorn-time.json
> +    "homepage": "https://github.com/popcorn-official/popcorn-desktop",
I will do it anyway.

2023-01-20 17:15 UTC, Zliced13 commented
/verify

2023-01-21 06:43 UTC, HUMORCE approved these changes

2023-01-21 07:27 UTC, merged