lively: Add version 2.0.5.0
ScoopInstaller/Extras pull request #10249
Opened 2023-01-16 01:04 UTC by Zliced13

A free and open-source software that allows users to set animated desktop wallpapers and screensavers. 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2023-01-16 01:04 UTC, Zliced13 commented
/verify

2023-01-16 01:11 UTC, Zliced13 commented
/verify

2023-01-17 11:34 UTC, HUMORCE requested changes

2023-01-17 11:34 UTC, HUMORCE commented on bucket/lively.json
> +    "pre_uninstall": "Remove-ItemProperty 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run' -Name 'Lively' -ErrorAction 'SilentlyContinue' -Force",
```suggestion
```

2023-01-17 11:34 UTC, HUMORCE commented on bucket/lively.json
> +            "Lively"
```suggestion
            "Lively Wallpaper"
```

2023-01-17 16:37 UTC, Zliced13 commented on bucket/lively.json
> +    "pre_uninstall": "Remove-ItemProperty 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run' -Name 'Lively' -ErrorAction 'SilentlyContinue' -Force",
Why not remove it? Why keep it there?

2023-01-19 05:54 UTC, HUMORCE approved these changes

2023-01-19 08:07 UTC, merged