ani-cli update 4.0
ScoopInstaller/Extras pull request #10336
Opened 2023-01-27 11:00 UTC by candrapersada

Closes #XXXX

Relates to #XXXX

- [ ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2023-01-27 23:11 UTC, port19x requested changes
The hash likely needs to be updated as well

2023-01-27 23:11 UTC, port19x commented on bucket/ani-cli.json
> +    "depends": "aria2",
```suggestion
    "depends": "aria2", "fzf"
```

2023-01-31 13:09 UTC, port19x requested changes

2023-01-31 13:09 UTC, port19x commented on bucket/ani-cli.json
>      "hash": "8dcefc128f239c2bb792986930deac947a6d5eda1815004832d999d80b719e68",
```suggestion
    "hash": "a98b78a3515c06014b572b3c49c1d8bfff6944d15b72fd8157c14ea1501ee0ab",
```

2023-02-02 07:49 UTC, port19x approved these changes

2023-02-04 19:38 UTC, port19x commented
- [x] someone
- [x] please
- [x] merge
- [x] (tasks to boost visibility lol)

2023-02-12 02:47 UTC, sitiom commented
Superseded by #10494. As a rule, `suggest` is recommended over `depends` for use cases where the dependency is installed outside Scoop.

2023-02-12 02:47 UTC, closed without merging