whkd: add version 0.1.0
ScoopInstaller/Extras pull request #10458
Opened 2023-02-08 00:07 UTC by LGUG2Z

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2023-02-08 00:31 UTC, LGUG2Z commented
/verify

2023-02-11 13:57 UTC, sitiom requested changes
Reformat manifest to 4 spaces.

2023-02-11 13:57 UTC, sitiom commented on bucket/whkd.json
> +  },
```suggestion
```
`whkd` can be used as a standalone tool.

2023-02-11 13:57 UTC, sitiom commented on bucket/whkd.json
> +    }
Add hash extraction
```suggestion
    },
    "hash": {
      "url": "$baseurl/checksums.txt"
    }
```

2023-02-11 14:55 UTC, LGUG2Z commented
Reformatted to 4 spaces!

2023-02-11 15:16 UTC, sitiom commented
/verify

2023-02-12 00:17 UTC, sitiom approved these changes

2023-02-12 00:17 UTC, merged