update install script, for mambaforge 22.11.1-2
ScoopInstaller/Extras pull request #10457
Opened 2023-02-07 19:27 UTC by chortbauer

As the 22.11.1-2 version of the mambaforge installer only installs into an empty directory, the installer is moved to the $env:TEMP directory befor installation. If the temporary path for the installer already exists, an error is thrown. After installation the installer is deleted as before.

Closes #10420

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2023-02-08 06:02 UTC, c-ortbauer approved these changes
Full disclosure: I am the author of this PR.
I made this PR at home with my private account and tested it on Windows 11.
Now I have tested it on my work PC running Windows 10.

2023-02-09 11:59 UTC, jaimergp commented
NSIS (what `constructor` uses to produce installers on Windows, hence Mambaforge) does not change the exit code if the installation fails (i.e. it always throws `0`). Would it be worth it to add post-install check? For example, testing for the existence of `python.exe`.

2023-02-10 04:02 UTC, elovelan commented
@jaimergp, I'm happy to write that post-install check if you'd be willing to merge to get this unblocked!

2023-02-10 04:05 UTC, elovelan commented
@jaimergp, I'll happily write that, but hopefully, we can get this merged to unblock it!

2023-02-10 04:22 UTC, elovelan commented
@jaimergp, the [NSIS Wiki indicates that NSIS _should_ be able to return a failure exit code](https://nsis.sourceforge.io/Docs/AppendixD.html#errorlevels). I'm happy to dig into this more if there's a chance that updating [constructor](https://github.com/conda/constructor) might resolve it. I realize that may be a risky proposition however if any software is relying on it always having a return code of 0, so I'm also happy to continue down the path of your original suggestion.

2023-02-13 11:27 UTC, jaimergp commented
I'd happily review PRs in `constructor`, yes! Maybe we do have to throw some `SetErrorLevel` calls here and there. I am not sure how broad `2 - Installation aborted by script` is either, but we'll get there. Thanks!

And yea, my suggestion shouldn't block this. We might have more than one issue ([see recent comment](https://github.com/conda-forge/miniforge/issues/421#issuecomment-1427009315)) anyway.

2023-02-27 02:40 UTC, elovelan commented
/verify

2023-03-17 11:00 UTC, jasongodev reviewed
Reminding myself to look at this again soon.

2023-03-17 15:01 UTC, jasongodev requested changes
Please use:

"checkver": "github"

2023-03-20 17:10 UTC, closed without merging