fixed wrong hash
ScoopInstaller/Extras pull request #10703
Opened 2023-03-09 09:37 UTC by dsm

fixed wrong hash 

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2023-03-13 14:11 UTC, jasongodev requested changes
This is not the correct way to update the hash.

The autoupdate hash routine is also incorrect.

Please create a new hash routine that detects the regex pattern of the current download file. The hash file mentioned contains a lot of hashes. You need to use regex to check for it.

2023-03-13 14:36 UTC, dsm commented
/verify

2023-03-14 08:42 UTC, dsm commented
thanks for review

2023-03-15 15:04 UTC, niheaven approved these changes

2023-04-09 23:46 UTC, merged