fluidsynth: Add version 2.3.3
ScoopInstaller/Extras pull request #11282
Opened 2023-05-15 22:17 UTC by superusercode

Closes #11280 

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2023-05-16 15:10 UTC, StarsbySea requested changes

2023-05-16 15:10 UTC, StarsbySea commented on bucket/fluidsynth.json
> +    "hash": "1781413b61e1f7ff3f360a1ecb81b320890e2dc11e19b2b9009951561cb366c6",
```suggestion
    "architecture": {
        "64bit": {
            "url": "https://github.com/FluidSynth/fluidsynth/releases/download/v2.3.2/fluidsynth-2.3.2-win10-x64.zip",
            "hash": "1781413b61e1f7ff3f360a1ecb81b320890e2dc11e19b2b9009951561cb366c6"
        }
    },
```

2023-05-16 15:10 UTC, StarsbySea commented on bucket/fluidsynth.json
> +        "url": "https://github.com/FluidSynth/fluidsynth/releases/download/v$version/fluidsynth-$version-win10-x64.zip"
```suggestion
        "architecture": {
            "64bit": {
                "url": "https://github.com/FluidSynth/fluidsynth/releases/download/v$version/fluidsynth-$version-win10-x64.zip"
            }
        }
```

2023-05-16 16:16 UTC, StarsbySea approved these changes

2023-06-15 08:47 UTC, HUMORCE approved these changes

2023-06-15 09:06 UTC, merged