delapp: Add version 1.0.1.2
ScoopInstaller/Extras pull request #11308
Opened 2023-05-20 11:13 UTC by entr0pia

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2023-05-22 09:06 UTC, StarsbySea commented
/verify

2023-06-08 06:40 UTC, StarsbySea requested changes

2023-06-08 06:40 UTC, StarsbySea commented on bucket/delapp.json
> +    "version":  "1.0.1.2",
```suggestion
    "version": "1.0.2",
```

2023-06-08 06:40 UTC, StarsbySea commented on bucket/delapp.json
> +    "url":  "https://github.com/differentrain/Delapp/releases/download/1.0.1/Delapp.zip",
```suggestion
    "url": "https://github.com/differentrain/Delapp/releases/download/1.0.2/Delapp.zip",
```

2023-06-08 12:19 UTC, StarsbySea commented
/verify

2023-06-08 14:09 UTC, StarsbySea requested changes

2023-06-08 14:09 UTC, StarsbySea commented on bucket/delapp.json
> +    "hash":  "7bc05877fa4b2dbe8fe0c5104b5e641fcfae9aefad74ef62d3aa61afb10f9d79",
```suggestion
    "hash": "e1613df86a3a4928b36100de1412af694cf84476e655b12c8f50ef9560c17227",
```

2023-06-08 14:16 UTC, StarsbySea approved these changes

2023-06-15 07:25 UTC, HUMORCE commented
https://github.com/differentrain/Delapp#requirement

suggests `extras/windowsdesktop-runtime` or `extras/windowsdesktop-runtime-lts`

```
    "suggest": {
        ".NET Desktop Runtime": "extras/windowsdesktop-runtime",
    },
```

2024-01-20 20:11 UTC, aliesbelik requested changes

2024-01-20 20:11 UTC, aliesbelik commented on bucket/delapp.json
> +    "license":  "MIT",
```suggestion
    "license":  "MIT",
    "suggest": {
        ".NET Desktop Runtime": "extras/windowsdesktop-runtime",
    },
```

2024-01-29 10:50 UTC, aliesbelik approved these changes

2024-01-29 10:51 UTC, aliesbelik commented
/verify

2024-01-29 11:00 UTC, merged