add zls 0.10.0
ScoopInstaller/Extras pull request #11376
Opened 2023-06-02 20:20 UTC by Slach

zig LSP server

2023-06-08 06:35 UTC, StarsbySea commented
/verify

2023-06-08 14:18 UTC, StarsbySea requested changes

2023-06-08 14:18 UTC, StarsbySea commented on bucket/zls.json
> +    "url": "https://install.zigtools.org/",
```suggestion

```

2023-06-08 16:13 UTC, Slach commented
/verify

2023-06-15 08:59 UTC, HUMORCE commented
main bucket.

2023-06-15 10:19 UTC, Slach commented
ok. create separate PR in MAIN bucket
https://github.com/ScoopInstaller/Main/pull/4886

2023-06-15 10:19 UTC, closed without merging