add terraform-ls 0.31.2
ScoopInstaller/Extras pull request #11375
Opened 2023-06-02 19:53 UTC by Slach

terraform-ls
Terraform LSP Server

2023-06-08 06:35 UTC, StarsbySea commented
/verify

2023-06-08 14:17 UTC, StarsbySea requested changes

2023-06-08 14:17 UTC, StarsbySea commented on bucket/terraform-ls.json
> +    "url":"https://github.com/hashicorp/terraform-ls",
```suggestion

```

2023-06-08 16:08 UTC, StarsbySea commented
/verify

2023-06-15 08:58 UTC, HUMORCE commented
main bucket.

2023-06-15 10:23 UTC, Slach commented
create separate PR in main bucket https://github.com/ScoopInstaller/Main/pull/4887

2023-06-15 10:23 UTC, closed without merging