buildcache: Add version v0.28.4
ScoopInstaller/Extras pull request #11628
Opened 2023-07-25 03:04 UTC by szymonj99

Closes #11627 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2023-07-25 03:04 UTC, szymonj99 commented
/verify

2023-07-25 06:49 UTC, HUMORCE requested changes

2023-07-25 06:49 UTC, HUMORCE commented on bucket/buildcache.json
> +    "license": "Zlb",
```suggestion
    "license": "Zlib",
```

correct short identifier

2023-07-25 06:49 UTC, HUMORCE commented on bucket/buildcache.json
> +        }
```suggestion
        }
```

64bit program

2023-07-25 06:49 UTC, HUMORCE commented on bucket/buildcache.json
> +            }
```suggestion
            }
```

2023-07-25 06:50 UTC, HUMORCE commented on bucket/buildcache.json
> +    },
```suggestion
    "checkver": “github”,
```

2023-07-25 12:56 UTC, szymonj99 commented
Issues should be fixed (unless I messed up 😄 ). Thank you!

2023-08-02 02:57 UTC, HUMORCE approved these changes

2023-08-02 02:57 UTC, HUMORCE commented
/verify

2023-08-02 03:05 UTC, merged