Update bt.json
ScoopInstaller/Extras pull request #11925
Opened 2023-09-24 00:03 UTC by neoOpus

attempt to make the persistent works.

Closes #XXXX

Relates to #XXXX

- [ ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2023-11-24 18:42 UTC, jasongodev commented
/verify

2023-11-30 11:07 UTC, HUMORCE requested changes
syntax

2023-11-30 11:07 UTC, HUMORCE commented on bucket/bt.json
> +    ]
```suggestion
    ],
```

2024-02-01 23:27 UTC, liny01-nbsa commented
Is this PR abandoned? I can create a new PR for this change if appropriate. It saves people the trouble for any manual post fixes.

2024-02-02 02:58 UTC, neoOpus commented
> Is this PR abandoned? I can create a new PR for this change if appropriate. It saves people the trouble for any manual post fixes.

Apologies for the confusion, but I need guidance on why this PR interests you. It fixes a bug, but I've forgotten the exact details of what it does.

2024-02-02 03:00 UTC, neoOpus commented
Oh now I recall, yeah I guess you came here after you've lost the config after the new update.

Please do what you think is more appropriate to fix this issue once for all for everyone!

2024-02-02 03:10 UTC, liny01-nbsa commented
Hi @neoOpus , nice to have you here. Looks @HUMORCE just need you to add a comma by the end of array close. If you still have the repo around, maybe you can still fix it, and have the PR merged as your change.

2024-02-02 13:11 UTC, liny01-nbsa commented
@neoOpus I used your change and created a new PR #12733. 😊

@HUMORCE , please check it out, and if it works, it closes both.

2024-02-02 21:41 UTC, aliesbelik commented
Fixed in #12733, closing this.

2024-02-02 21:41 UTC, closed without merging