bruno: add version 0.16.5
ScoopInstaller/Extras pull request #11970
Opened 2023-10-01 20:18 UTC by Zottelchen

This PR adds the bruno manifest.

Closes #11969

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2023-10-07 04:06 UTC, Zottelchen commented on bucket/bruno.json
> +    "checkver": "github",
👍

2023-10-07 07:32 UTC, jonz94 approved these changes

2023-10-07 07:34 UTC, jonz94 commented
/verify

2023-10-07 07:57 UTC, jonz94 commented
I think the test failed because the latest version of `bruno` is 0.21.0, not due to any issues with the code.

So, updating the version and the hash should make the test pass.

2023-10-17 13:16 UTC, Zottelchen commented
/verify

2023-10-23 13:04 UTC, helloanoop commented
Hi, This is Anoop. Creator of Bruno.

Looking forward to have this merged!

2023-11-25 05:50 UTC, thesobercoder commented
@helloanoop Hi Anoop, any idea when this will be merged. Eagerly waiting!!

2023-11-25 15:46 UTC, tech189 commented on bucket/bruno.json
> +    "description": "Opensource IDE For Exploring and Testing Api's (lightweight alternative to postman/insomnia)",
```suggestion
    "description": "Open source IDE for exploring and testing APIs (lightweight alternative to Postman/Insomnia)",
```
Improvement to spelling in description

2023-11-25 16:04 UTC, tech189 commented
Making a note that Bruno stores config data in `AppData\Roaming\bruno` so nothing to persist.

@Zottelchen could you update this manifest to the latest version please?

2023-11-25 18:04 UTC, Zottelchen commented
@tech189 Sure, done.

2023-11-25 18:04 UTC, Zottelchen commented
/verify

2023-11-25 18:12 UTC, tech189 requested changes

2023-11-25 18:12 UTC, tech189 commented on bucket/bruno.json
> +        "github": "https://github.com/usebruno/bruno"
```suggestion
            "hash": "98941b455b71d7c8c8bfff5c448c0587960962d947a2e37665e411bffb95d4d0"
        }
    },
    "extract_dir": "win-unpacked",
    "shortcuts": [
        [
            "Bruno.exe",
            "Bruno"
        ]
    ],
    "checkver": {
        "github": "https://github.com/usebruno/bruno"
```


Almost there, could you move `extract_dir` out of architecture and put it before `shortcuts` as per https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md#for-scoop-buckets ? That way if there's a new architecture in the future, the same directory can be used to extract for both.

2023-11-25 21:08 UTC, tech189 approved these changes

2023-11-25 21:08 UTC, merged

2023-11-25 21:08 UTC, tech189 commented
Thank you for your contribution!