swift-mesonlsp: add v2.4.4
ScoopInstaller/Extras pull request #11989
Opened 2023-10-05 09:59 UTC by shanoaice

Closes #11988.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2023-11-24 18:41 UTC, jasongodev commented
/verify

2023-11-25 01:29 UTC, shanoaice commented
Ooh, there's been an update, let me fix this.

2024-01-29 19:09 UTC, aliesbelik requested changes
Please update to the latest version as well.

2024-01-29 19:09 UTC, aliesbelik commented on bucket/swift-mesonlsp.json
> +    "homepage": "https://github.com/JCWasmx86/Swift-MesonLSP#readme",
```suggestion
    "homepage": "https://github.com/JCWasmx86/Swift-MesonLSP",
```

2024-01-29 19:09 UTC, aliesbelik commented on bucket/swift-mesonlsp.json
> +    },
```suggestion
    "checkver": "github",
```

2024-02-11 14:24 UTC, aliesbelik approved these changes

2024-02-11 14:26 UTC, aliesbelik commented
/verify

2024-02-11 14:29 UTC, merged