windowsdesktop-runtime: Update info
ScoopInstaller/Extras pull request #12238
Opened 2023-11-15 06:25 UTC by b4imetu

Closes #XXXX

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2023-11-15 06:25 UTC, b4imetu commented
/verify

2023-11-28 17:38 UTC, HUMORCE requested changes

2023-11-28 17:38 UTC, HUMORCE commented on bucket/windowsdesktop-runtime.json
> +    "notes": "You can now remove this installer with 'scoop uninstall -p windowsdesktop-runtime'",
```suggestion
    "notes": "You can now remove this installer with 'scoop uninstall windowsdesktop-runtime'",
```
No persistence data has been created.

2023-11-29 01:42 UTC, b4imetu commented
https://github.com/ScoopInstaller/Versions/pull/1457
Please also take a look at this PR, as a non-latest but Long Term Support version supplement

2023-11-30 08:12 UTC, HUMORCE commented
#12363

2023-11-30 08:12 UTC, closed without merging