feat(alacritty): add context menu
ScoopInstaller/Extras pull request #13358
Opened 2024-05-26 19:05 UTC by rafaeloledo

Inspired on the #12997, add more registry entries to work with right click on folder directly. Alter the pop-up text to be `Open with Alacritty` instead of `Open Alacritty here` to be cohesive with `sublime-text` example.

Closes #12997

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2024-05-26 21:19 UTC, rafaeloledo commented
/verify

2024-06-01 00:23 UTC, jenbroek requested changes

2024-06-01 00:23 UTC, jenbroek commented on scripts/alacritty/install-context.reg
> +@="\"$alacritty\" --working-directory %v"
You need to use `\"%v\"` here (see: https://github.com/alacritty/alacritty/pull/7875#issuecomment-2024441897). To be sure, I also tested this by creating a directory named '力 九' (just copied some random Hanzi). With just `%v`, Alacritty won't launch, but it does with `\"%v\"`. I imagine the same would hold true for the Sublime Text registry script.

2024-06-01 01:33 UTC, rafaeloledo commented on scripts/alacritty/install-context.reg
> +@="\"$alacritty\" --working-directory %v"
Thank you for clarifying this. I think that's no solution for root dir, it depends on microsoft supporting Unicode sequences in the registry. Closing. Feel free to merge the diffs in your PR.

2024-06-01 01:34 UTC, closed without merging