picview: Add version 2.2.7
ScoopInstaller/Extras pull request #13389
Opened 2024-06-03 13:50 UTC by Ruben2776

Relates to #13388

- [ ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2024-06-03 20:47 UTC, Ruben2776 commented
/verify

2024-06-03 21:39 UTC, Ruben2776 commented
/verify

2024-06-03 21:54 UTC, Ruben2776 commented
/verify

2024-06-03 22:27 UTC, aliesbelik commented on bucket/picview.json
> +            "extract_dir": ""
```suggestion
            "hash": "DD52E9916A38B442DB57B41B7A5737F09299455A9F2C14C4E095EC74998B360D"
```

2024-06-03 22:27 UTC, aliesbelik commented on bucket/picview.json
> +            "extract_dir": ""
```suggestion
            "hash": "b463c8b0795508932271f6c9de377fa13a96d1b96d482950d7fd702bc32ae3b3"
```

2024-06-03 22:30 UTC, aliesbelik reviewed
`extract_dir` not necessary here and could be removed, both from download and autoupdate sections.

2024-06-03 22:30 UTC, aliesbelik commented on bucket/picview.json
> +                "extract_dir": ""
```suggestion
                "url": "https://github.com/Ruben2776/PicView/releases/download/$version/PicView-v.$version-win-arm64.zip"
```

2024-06-03 22:30 UTC, aliesbelik commented on bucket/picview.json
> +                "extract_dir": ""
```suggestion
				"url": "https://github.com/Ruben2776/PicView/releases/download/$version/PicView-v.$version-win-x64.zip"
```

2024-06-03 23:17 UTC, Ruben2776 commented
/verify

2024-06-04 05:00 UTC, aliesbelik commented on bucket/picview.json
> +				"url": "https://github.com/Ruben2776/PicView/releases/download/$version/PicView-v.$version-win-x64.zip"
```suggestion
                "url": "https://github.com/Ruben2776/PicView/releases/download/$version/PicView-v.$version-win-x64.zip"

```

2024-06-04 05:01 UTC, aliesbelik requested changes
> Error: [-] any leading whitespace consists only of spaces (excepting makefiles) 216ms (215ms|1ms)

2024-06-04 05:58 UTC, niheaven commented on bucket/picview.json
> +    "description": "PicView is a fast, free and fully customizable image viewer for Windows 10 and 11.",
```suggestion
    "description": "A fast, free and fully customizable image viewer for Windows 10 and 11",

```

2024-06-04 06:10 UTC, aliesbelik approved these changes

2024-06-05 02:45 UTC, aliesbelik commented
/verify

2024-06-05 02:50 UTC, merged