media-downloader: Add version 4.7.0
ScoopInstaller/Extras pull request #13436
Opened 2024-06-09 17:10 UTC by ahmed-0011

Add [media-downloader](https://github.com/mhogomchungu/media-downloader), a Qt/C++ front end to yt-dlp, youtube-dl, gallery-dl, lux, you-get, svtplay-dl, aria2c, wget and safari books..

Closes https://github.com/ScoopInstaller/Extras/issues/11167

* [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2024-06-10 00:03 UTC, aliesbelik commented
Relates to mhogomchungu/media-downloader#266.

2024-06-10 00:09 UTC, aliesbelik requested changes
Formatting & extract_dir autoupdate.

2024-06-10 00:10 UTC, aliesbelik commented on bucket/media-downloader.json
> +    "shortcuts": [["media-downloader.exe", "media-downloader"]],
```suggestion
    "shortcuts": [
        [
            "media-downloader.exe",
            "Media Downloader"
        ]
    ],
```

2024-06-10 00:10 UTC, aliesbelik commented on bucket/media-downloader.json
> +        "url": "https://github.com/mhogomchungu/media-downloader/releases/download/$version/MediaDownloader-$version.zip"
```suggestion
        "url": "https://github.com/mhogomchungu/media-downloader/releases/download/$version/MediaDownloader-$version.zip",
        "extract_dir": "MediaDownloader-$version"
```

2024-06-10 00:10 UTC, aliesbelik requested changes
Formatting & extract_dir autoupdate.

2024-06-10 16:47 UTC, ahmed-0011 commented
\verify

2024-06-10 16:48 UTC, ahmed-0011 commented
/verify

2024-06-11 11:28 UTC, aliesbelik approved these changes

2024-06-11 12:07 UTC, merged