kando: Add version 1.1.0
ScoopInstaller/Extras pull request #13563
Opened 2024-07-03 20:55 UTC by Akasiek

Closes #13365

- [ ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2024-07-03 20:55 UTC, Akasiek commented
/verify

2024-07-03 22:27 UTC, aliesbelik commented
Please fix validation issue(s) and follow the [order of fields as per Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md#for-scoop-buckets).

2024-07-03 22:41 UTC, aliesbelik requested changes
And a bit more.

2024-07-03 22:41 UTC, aliesbelik commented on bucket/kando.json
> +    },
```suggestion
    "checkver": "github",
```

Since same GH link already used as `homepage`.

2024-07-03 22:41 UTC, aliesbelik commented on bucket/kando.json
> +    "hash": "04a85258ef1d068aa7bbfd2ff661b45f5e13a42d918856a5d7f696e7fc51e9eb",
```suggestion
    "architecture": {
        "64bit": {
            "url": "https://github.com/kando-menu/kando/releases/download/v1.1.0/Kando-win32-x64-1.1.0.zip",
            "hash": "04a85258ef1d068aa7bbfd2ff661b45f5e13a42d918856a5d7f696e7fc51e9eb"
        }
    },
```

2024-07-03 22:41 UTC, aliesbelik commented on bucket/kando.json
> +        "url": "https://github.com/kando-menu/kando/releases/download/v$version/Kando-win32-x64-$version.zip"
```suggestion
        "architecture": {
            "64bit": {
                "url": "https://github.com/kando-menu/kando/releases/download/v$version/Kando-win32-x64-$version.zip"
            }
        }
```

2024-07-03 22:53 UTC, Akasiek commented
Sorry for this newline stuff. VSCode keeps deleting it...

2024-07-04 01:54 UTC, aliesbelik commented
/verify

2024-07-04 02:03 UTC, aliesbelik approved these changes

2024-07-04 10:33 UTC, Akasiek commented
@aliesbelik Kando stores all data in the `%APPDATA%\Kando` folder. Should I add this information to `notes` like in Kanri?

2024-08-29 03:14 UTC, aliesbelik commented
/verify

2024-08-29 03:19 UTC, merged