reable: Add version 2.21.4
ScoopInstaller/Extras pull request #13772
Opened 2024-08-09 05:56 UTC by Mrbunker

https://github.com/reqable/reqable-app/
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2024-08-12 09:04 UTC, aliesbelik requested changes

2024-08-12 09:04 UTC, aliesbelik commented on bucket/reqable.json
> +    "license": "Unknown",
```suggestion
    license": {
        "identifier": "Proprietary",
        "url": "https://reqable.com/en-US/docs/license/"
    },
    "notes": [
        "Free community version: almost all features are free, but the number of usage is limited.",
        "For commercial use, you need to purchase a license."
    ],
```

2024-08-12 09:05 UTC, aliesbelik commented
Any data/configuration to [persist](https://github.com/ScoopInstaller/Scoop/wiki/Persistent-data)?

2024-08-12 09:58 UTC, Mrbunker commented
> Any data/configuration to [persist](https://github.com/ScoopInstaller/Scoop/wiki/Persistent-data)?

the data is stored in <username>\AppData\Roaming\Reqable

2024-08-16 14:38 UTC, aliesbelik approved these changes

2024-08-16 14:39 UTC, aliesbelik commented
/verify

2024-08-16 14:43 UTC, merged