KubeVPN: Add version 2.2.17
ScoopInstaller/Extras pull request #13924
Opened 2024-08-31 10:02 UTC by wencaiwulue

Add package kubevpn: KubeVPN offers a Cloud Native Dev Environment that connects to kubernetes cluster network.

- [ x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2024-08-31 15:07 UTC, aliesbelik requested changes

2024-08-31 15:07 UTC, aliesbelik commented on bucket/kubevpn.json
> +    "bin": "kubevpn.exe",
```suggestion
            "hash": "4513683410566628f39c2f423e066c4903bb7b3abd7a80a1ba6115e8cc65115d"
        },
        "32bit": {
            "url": "https://github.com/kubenetworks/kubevpn/releases/download/v2.2.17/kubevpn_v2.2.17_windows_386.zip",
            "hash": "2050af3cd8e1e2a717a7f74610d881bad2bbae6d8ff4e7670c5c5ef2a95c8e9b"
        },
        "arm64": {
            "url": "https://github.com/kubenetworks/kubevpn/releases/download/v2.2.17/kubevpn_v2.2.17_windows_arm64.zip",
            "hash": "cce520fe2d44761d2ca679fbfaa886909d5664f8c3199aca8b06e75868b2bdc6"
        }
    },
    "extract_dir": "bin",
    "bin": "kubevpn.exe",
```

2024-08-31 15:07 UTC, aliesbelik commented on bucket/kubevpn.json
> +    "homepage": "https://github.com/kubenetworks/kubevpn",
```suggestion
    "homepage": "https://www.kubevpn.cn/",
```

2024-08-31 15:07 UTC, aliesbelik commented on bucket/kubevpn.json
> +                "extract_dir": "bin"
```suggestion
                "url": "https://github.com/kubenetworks/kubevpn/releases/download/v$version/kubevpn_v$version_windows_amd64.zip"
            },
            "32bit": {
                "url": "https://github.com/kubenetworks/kubevpn/releases/download/v$version/kubevpn_v$version_windows_386.zip"
            },
            "arm64": {
                "url": "https://github.com/kubenetworks/kubevpn/releases/download/v$version/kubevpn_v$version_windows_arm64.zip"
```

2024-09-01 01:44 UTC, wencaiwulue commented
@aliesbelik it's very kind of you, thianks a lot ~

2024-09-02 01:16 UTC, wencaiwulue commented
fix 
```txt
Error: [-] files end with a newline 68ms (67ms|1ms)
```

by https://github.com/ScoopInstaller/Extras/commit/9c46f210d22b0144b77c92581225cff36f7e85ee

2024-09-02 03:06 UTC, aliesbelik commented
/verify

2024-09-03 09:58 UTC, wencaiwulue commented
solve #13943

2024-09-06 20:38 UTC, aliesbelik commented
/verify

2024-09-06 20:41 UTC, aliesbelik approved these changes

2024-09-06 20:42 UTC, merged