Update license in komorebi.json for v0.1.29
ScoopInstaller/Extras pull request #14097
Opened 2024-09-28 05:23 UTC by LGUG2Z

Ensures that the license accurately reflects the new license used for v0.1.29.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2024-10-03 11:34 UTC, thesobercoder commented
Please merge this.

2024-10-06 17:50 UTC, aliesbelik requested changes
For non-SPDX licenses, include a link to the license.

2024-10-06 17:50 UTC, aliesbelik commented on bucket/komorebi.json
> +    "license": "Komorebi",
```suggestion
    "license": {
        "identifier": "Komorebi",
        "url": "https://github.com/LGUG2Z/komorebi/blob/master/LICENSE.md"
    },
```

2024-10-06 20:07 UTC, aliesbelik approved these changes

2024-10-06 20:08 UTC, aliesbelik commented
/verify

2024-10-06 20:12 UTC, merged

2024-11-05 05:24 UTC, nahid6970 commented
why the hell its still not online ?? its already online in winget months ago. is the scoop maintainers having some personal issues? i thought scoop package managers is millions time better than winget. but oh i was so wrong. a version that is already updated to winget month ago and here we are.