sshs: Add version 4.5.1
ScoopInstaller/Extras pull request #14145
Opened 2024-10-04 21:06 UTC by xd-mau5

Closes #13003

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2024-10-04 21:45 UTC, aliesbelik requested changes
- Inline renaming via `#/` is more laconic and makes `pre_install` unnecessary.
- Default regex for github link in `checkver` is enough.

2024-10-04 21:45 UTC, aliesbelik commented on bucket/sshs.json
> +            "url": "https://github.com/quantumsheep/sshs/releases/download/4.5.1/sshs-windows-amd64.exe",
```suggestion
            "url": "https://github.com/quantumsheep/sshs/releases/download/4.5.1/sshs-windows-amd64.exe#/sshs.exe",
```

2024-10-04 21:45 UTC, aliesbelik commented on bucket/sshs.json
> +            "url": "https://github.com/quantumsheep/sshs/releases/download/4.5.1/sshs-windows-arm64.exe",
```suggestion
            "url": "https://github.com/quantumsheep/sshs/releases/download/4.5.1/sshs-windows-arm64.exe#/sshs.exe",
```

2024-10-04 21:45 UTC, aliesbelik commented on bucket/sshs.json
> +                "url": "https://github.com/quantumsheep/sshs/releases/download/$version/sshs-windows-amd64.exe"
```suggestion
                "url": "https://github.com/quantumsheep/sshs/releases/download/$version/sshs-windows-amd64.exe#/sshs.exe"
```

2024-10-04 21:45 UTC, aliesbelik commented on bucket/sshs.json
> +                "url": "https://github.com/quantumsheep/sshs/releases/download/$version/sshs-windows-arm64.exe"
```suggestion
                "url": "https://github.com/quantumsheep/sshs/releases/download/$version/sshs-windows-arm64.exe#/sshs.exe"
```

2024-10-04 21:45 UTC, aliesbelik commented on bucket/sshs.json
> +    ],
```suggestion
    },
```

2024-10-04 21:45 UTC, aliesbelik commented on bucket/sshs.json
> +    },
```suggestion
    "checkver": "github",
```

2024-10-04 21:47 UTC, aliesbelik commented
Looks like could be promoted into the `Main` bucket instead, since fits the [Main criteria](https://github.com/ScoopInstaller/Scoop/wiki/Criteria-for-including-apps-in-the-main-bucket).

2024-10-04 22:23 UTC, xd-mau5 commented
Should i make the pull request in Main then?

2024-10-04 23:03 UTC, aliesbelik commented
> Should i make the pull request in Main then?

I'm not maintainer of Main so I couldn't transfer your request and pr, but if you are interested in promoting requested tool into Main instead Extras, I suppose this would be a more suitable place.
Otherwise could be merged into Extras, with the requested changes.

2024-10-04 23:19 UTC, xd-mau5 commented
/review

2024-10-06 16:29 UTC, aliesbelik commented
/verify

2024-10-06 16:35 UTC, aliesbelik approved these changes

2024-10-06 16:35 UTC, merged