Add Open TV
ScoopInstaller/Extras pull request #14245
Opened 2024-10-18 19:55 UTC by Fredolx

Added Open TV to Extras

- [ X ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2024-12-29 16:55 UTC, rasa commented
/verify

2024-12-30 08:59 UTC, rasa commented
@Fredolx Checkver is failing. Please advise. Thx.

2025-01-13 04:47 UTC, Fredolx commented
Should be fixed now

2025-01-13 09:38 UTC, bt4ibwem8 commented
/verify

2025-01-13 10:25 UTC, bt4ibwem8 commented
Closes #14726

2025-01-13 10:31 UTC, bt4ibwem8 commented
/verify

2025-01-13 10:40 UTC, bt4ibwem8 commented
@Fredolx 
I linked package request, but does not work. Probably it is needed do it by you, as the creator of this PR

2025-01-13 16:30 UTC, aliesbelik requested changes
- Fix EOF.
- Follow the standard order of fields in the json file, as per [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md#for-scoop-buckets).

2025-01-13 16:30 UTC, aliesbelik commented on bucket/open-tv.json
> +    },
```suggestion
    "checkver": "github",
```

Enough since GH link already used as homepage.

2025-01-14 04:34 UTC, Fredolx commented
I fixed the order of fields and applied the code suggestion. I am not sure about the package request, do you want me to create one or add a comment to the one you linked?

2025-01-14 07:03 UTC, merged

2025-01-16 00:32 UTC, aliesbelik commented
> I am not sure about the package request, do you want me to create one or add a comment to the one you linked?

Not actual more.
Someone has created one (#14726).

As per the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md) the normal flow is to create first [request for new app/package](https://github.com/ScoopInstaller/Extras/issues/new/choose).