kubespy: Add version 0.6.3
ScoopInstaller/Extras pull request #14361
Opened 2024-11-05 15:30 UTC by cowwoc

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2024-11-06 01:55 UTC, aliesbelik commented
As a non-GUI tool could be submitted into the `main` bucket instead, since meeting the [Main criteria](https://github.com/ScoopInstaller/Scoop/wiki/Criteria-for-including-apps-in-the-main-bucket).

2024-11-06 01:56 UTC, aliesbelik commented
Please add arm64 version and hash autoupdate section as well.

2024-11-06 04:18 UTC, cowwoc commented
@aliesbelik Thanks for the head's up regarding the `main` bucket. I didn't know it was an option.

Regarding the hash, does `GitHub` post sha256 values for all downloads? I couldn't find any reference for this...

2024-11-06 04:42 UTC, aliesbelik requested changes
Adding arm64 version and hash autoupdate.

2024-11-06 04:42 UTC, aliesbelik commented on bucket/kubespy.json
> +            }
```suggestion
            },
            "arm64": {
                "url": "https://github.com/pulumi/kubespy/releases/download/v$version/kubespy-v$version-windows-arm64.tar.gz"
            }
```

2024-11-06 04:42 UTC, aliesbelik commented on bucket/kubespy.json
> +        }
```suggestion
        },
        "hash": {
            "url": "$baseurl/checksums.txt"
        }
```

2024-11-06 04:42 UTC, aliesbelik commented on bucket/kubespy.json
> +        }
```suggestion
        },
        "arm64": {
            "url": "https://github.com/pulumi/kubespy/releases/download/v0.6.3/kubespy-v0.6.3-windows-arm64.tar.gz",
            "hash": "d0bb9ed65b4b5869280e6030058c8eed32d4f6590ceff666cf4221429745ea84"
        }
```

2024-11-07 13:37 UTC, cowwoc commented
Thank you!

2024-11-07 13:37 UTC, cowwoc commented
@aliesbelik Should I close this PR and open a new one against the main bucket?

2024-11-12 12:36 UTC, aliesbelik approved these changes

2024-11-12 12:37 UTC, aliesbelik commented
/verify

2024-11-12 12:44 UTC, aliesbelik commented
> Should I close this PR and open a new one against the main bucket? Or are we able to move it over somehow?

I'm not maintainer of Main so I couldn't transfer your request.
If you feel enthusiastic enough, please re-create PR with final version of manifest in Main.
Otherwise looks good and could be merged into Extras.

2024-11-12 13:25 UTC, cowwoc commented
Let's leave it in extra. You can go ahead with the merge. Thanks again for your help!

2024-11-13 15:33 UTC, merged