scoop-search: Add version 0.5.0
ScoopInstaller/Extras pull request #4106
Opened 2020-05-21 12:24 UTC by tokiedokie

I made yet another  `scoop search` called `scoop-search`

2021-01-15 03:09 UTC, earnestma requested changes

2021-01-15 03:09 UTC, earnestma commented on bucket/scoop-search.json
> +    "description": "yet another scoop search",
```suggestion
    "version": "0.6.5",
    "description": "Yet another scoop search",
    "homepage": "https://github.com/tokiedokie/scoop-search",
    "license": "MIT",
    "url": "https://github.com/tokiedokie/scoop-search/releases/download/v0.6.5/scoop-search.exe",
```

version -> description -> homepage -> license ...

2021-01-15 03:09 UTC, earnestma commented on bucket/scoop-search.json
> +}
```suggestion
}

```

Insert final newline for tests to pass

2021-12-31 20:30 UTC, rashil2000 commented
An app called `scoop-search` is already present in Main. Can you select a different name?

2022-03-16 08:46 UTC, closed without merging