lite: Add version 1.11
ScoopInstaller/Extras pull request #4612
Opened 2020-08-20 08:49 UTC by sebmaynard

Closes #4494

2020-08-20 08:58 UTC, Ash258 requested changes

2020-08-20 08:58 UTC, Ash258 commented on bucket/lite.json
> +    "description": " A lightweight text editor written in Lua ",
```suggestion
    "description": "A lightweight text editor",
```

2020-08-20 08:58 UTC, Ash258 commented on bucket/lite.json
> +    "url": "https://github.com/rxi/lite/releases/download/v1.11/lite.zip",
```suggestion
    "architecture": {
        "64bit": {
            "url": "https://github.com/rxi/lite/releases/download/v1.11/lite.zip",
            "hash": "da3701cf6985bc493cb11b37556325551c7ce8606f5502ff3f15199039835eef"
        }
    },
```

2020-08-20 08:58 UTC, Ash258 commented on bucket/lite.json
> +        "url": "https://github.com/rxi/lite/releases/download/v$version/lite.zip"
```suggestion
        "architecture": {
            "64bit": {
                "url": "https://github.com/rxi/lite/releases/download/v$version/lite.zip"
            }
        }
```

2020-09-18 18:58 UTC, ProfElements commented
Sorry to ressurect this old thread. Can I do this since it have been dead for 27 days?

2020-09-19 12:32 UTC, sebmaynard commented
@ProfElements of course, sorry life got in my way...

2020-09-19 20:03 UTC, ProfElements commented
:+1: Thank you for confirmation

2021-10-30 17:14 UTC, pratikpc commented
@sebmaynard could you add Persist support?

2021-11-11 06:30 UTC, rashil2000 commented
Closing in favour of #7301

2021-11-11 06:30 UTC, closed without merging