tartube: Add version 2.1.070
ScoopInstaller/Extras pull request #4699
Opened 2020-09-03 16:47 UTC by ghost-420

2020-09-03 16:53 UTC, Ash258 requested changes

2020-09-03 16:53 UTC, Ash258 commented on bucket/tartube.json
> +            "persist": [
Persist is not allowed in architecture

2020-09-07 16:42 UTC, Ash258 requested changes
- Investigate how to conifgure data dir automatically into persist folder

![image](https://user-images.githubusercontent.com/13260377/92407027-ccd28500-f139-11ea-8c69-f308c1062e06.png)

![image](https://user-images.githubusercontent.com/13260377/92407035-d360fc80-f139-11ea-926f-53358701e352.png)

2020-09-16 07:57 UTC, ghost-420 commented
* Tartube's default data folder setting does not reside where the Scoop installation does; below screenshot is how you can retrieve the default data folder currently.
![python3_HgERgVbM34](https://user-images.githubusercontent.com/29991266/93308722-78717a00-f7b7-11ea-804d-df45e3b0f422.png)
![python3_V53kAre7FY](https://user-images.githubusercontent.com/29991266/93307472-db621180-f7b5-11ea-9381-dfe55a254cc9.png)
I 'scoop uninstall -p tartube', reinstalled tartube, then moved the directory from E:\Videos\Tartube to E:\Tartube
![python3_9BJRHW38Bx](https://user-images.githubusercontent.com/29991266/93308300-f08b7000-f7b6-11ea-9e19-0e83edd61b6e.png)
![OKKmZYSaFd](https://user-images.githubusercontent.com/29991266/93308307-f1bc9d00-f7b6-11ea-9edb-469c66800e61.png)
![D873JIZHt6](https://user-images.githubusercontent.com/29991266/93308312-f3866080-f7b6-11ea-8c2b-e9fee0c7882b.png)
* youtube-dl is already persisted.
![FLXvLHSkZe](https://user-images.githubusercontent.com/29991266/93307426-ce452280-f7b5-11ea-8e6c-6421597ba334.png)

2020-09-16 08:13 UTC, Ash258 commented
> Tartube's default data folder setting does not reside where the Scoop installation does; below screenshot is how you can retrieve the default data folder currently.

... It is configurable

![image](https://user-images.githubusercontent.com/13260377/93310532-32430780-f805-11ea-8b8e-50950458ad16.png)


> youtube-dl is already persisted.

Why you cannot use system-wide youtube-dl instead of some random mingw version?

2020-09-27 20:23 UTC, axcore commented
Hi, I'm the Axmud dev.

@Ash258 asks:

>Why you cannot use system-wide youtube-dl instead of some random mingw version?

At the moment, Tartube does not offer many choices for installation on MS WIndows. The reason is this: I am assuming that everyone is using the MS WIndows installer I created.

If there is another installation method (using Scoop), then I can add support for that. Just tell me what changes you need. For example this:

`"data_dir": "C:\\Users\\vagrant\\scoop\\persist\\tartube\\cosi`

All of that could be added to the code, then future releases of Tartube will work with Scoop, without creating any more work for you.

2021-11-09 09:29 UTC, Aankhen commented
I’m not sure I understand the issue, but I wanted to chime in to say it would be great if we took up @axcore’s offer to work together to make Tartube more Scoop-friendly, with a view towards improving and merging this PR. I’m sure I’m not the only one who’d love to see it in Scoop, and it would be a shame to let all this work go to waste.

2021-11-09 12:22 UTC, rashil2000 commented
Thanks for the reminder @Aankhen 

@axcore sorry for the delay here, but did you get around to configuring the portable version to use the same data_dir as the application itself?

2021-11-09 17:29 UTC, axcore commented
> Thanks for the reminder @Aankhen
> 
> @axcore sorry for the delay here, but did you get around to configuring the portable version to use the same data_dir as the application itself?

I am happy to help you with any changes you need.

But, remember: I have never used Scoop and know nothing about it. Is there a reason why the user should not choose their own data directory? 

(Tartube's configuration file already lives in the installation folder, by the way.)

2021-11-09 17:36 UTC, rashil2000 commented
Scoop aims to be portable, self-contained installer and for portable apps it's much preferred to have all the user files in the installation directory itself (at least as a default).

2021-11-10 06:04 UTC, pratikpc commented
Closing as ghost-420:tartube has been deleted.

@Aankhen that is indeed a great idea and I would recommend you to work on a new PR instead so we can add tartube to Scoop quickly.

2021-11-10 06:04 UTC, closed without merging