trillian: Add version 6.3.0.6
ScoopInstaller/Extras pull request #4806
Opened 2020-09-23 20:29 UTC by stasjok

Trillian
https://www.trillian.im

2020-09-24 05:51 UTC, Ash258 requested changes
Blocked by lukesampson/scoop#3828

2020-09-24 05:51 UTC, Ash258 commented on bucket/trillian.json
> +        "}"
```suggestion
        "if (!(Test-Path \"$persist_dir\\trillian.ini\")) {",
        "   Set-Content \"$dir\\trillian.ini\" ('[General]', 'Use User Directory=0', 'Global Directory=users\\global\\') -Encoding Ascii",
        "}"
```

2020-09-24 05:51 UTC, Ash258 commented on bucket/trillian.json
> +        "regex": "\"windows\",\\s*([\\d.]+),\\s*([\\d]+),\\s*\"[^\"]+\",\\s+false",
```suggestion
        "regex": "\"windows\",\\s*([\\d.]+),\\s*([\\d]+),\\s*\".*?\",\\s*false",
```

2021-12-30 10:38 UTC, rashil2000 commented
The latest URL is https://trillian.im/get/windows/6.5/trillian-v6.5.0.18.exe, but 7z cannot extract it. @issaclin32 does it work for you?

2021-12-30 11:13 UTC, issaclin32 commented
> The latest URL is https://trillian.im/get/windows/6.5/trillian-v6.5.0.18.exe, but 7z cannot extract it. @issaclin32 does it work for you?

Cannot extract either. (using 7-zip 21.07)

2021-12-30 14:16 UTC, stasjok commented
I've updated autoupdate URL.

2021-12-30 14:18 UTC, rashil2000 commented
Have you tested the manifest by installing it?

2021-12-30 14:22 UTC, stasjok commented
> Have you tested the manifest by installing it?

I've updated version that was already installed for me on my computer with this manifest. Looks like versions 6.4 and earlier are downloaded from ceruleanstudios.com, but since 6.5 they moved to trillian.im. So autoupdate was broken. But thanks for your message I noticed it and fixed for now.

2021-12-30 14:31 UTC, rashil2000 commented
/verify

2021-12-30 14:33 UTC, merged