Added switcheroo 0.10.0-beta.1
ScoopInstaller/Extras pull request #5003
Opened 2020-10-29 05:36 UTC by snowman

2020-10-29 06:35 UTC, Ash258 requested changes
The portable version does not persiste anything, which indicate two things:

1. It is not portable
1. You did not add it.

```powershell
remove-item bucket/switcheroo.json
git mv bucket/switcherro-portable.json bucket/switcheroo.json
```

2020-10-29 06:47 UTC, snowman commented
Should it be below format

```json
{
    "version": "0.10.0-beta.1",
    "description": "The humble incremental-search task switcher for Windows",
    "homepage": "https://github.com/kvakulo/Switcheroo",
    "license": "GPL-3.0-only",
    "url": "https://github.com/kvakulo/Switcheroo/releases/download/v0.10.0-beta.1/switcheroo-setup.exe",
    "hash": "cca4227fd7fab5e908f18f78d2073b6f3fbbbd89599368c250c9e80a8d7ba9b9",
    "innosetup": true,
    "bin": "switcheroo.exe",
    "shortcuts": [
        [
            "switcheroo.exe",
            "switcheroo"
        ]
    ]
}
```

or just 
```powershell
remove-item bucket/switcheroo.json
git mv bucket/switcheroo-portable.json bucket/switcheroo.json
```

2020-10-29 06:48 UTC, Ash258 commented
What? The question does not make sense...

2020-10-29 06:58 UTC, snowman commented
There are two versions: `switcheroo-setup.exe` and `switcheroo-portable.zip`

So if it's not portable, then I guess should download the `switcheroo-setup.exe` version instead of `git mv`?

I don't know how to contribute (have checked README.md), and I kind of don't know what inno-setup is. If you think either way is okay, then let it go. :p

2020-10-29 07:00 UTC, Ash258 commented
The portable as proposed in the two lines of powershell.

Keep it as it is.

2020-10-30 08:33 UTC, Ash258 requested changes

2020-10-30 08:33 UTC, Ash258 commented on bucket/switcheroo.json
> +        "github": "https://github.com/kvakulo/Switcheroo"
```suggestion
        "url": "https://github.com/kvakulo/Switcheroo/releases",
        "regex": "tag/v([\\w.-]+)"
```

2020-10-30 08:33 UTC, Ash258 commented on bucket/switcheroo.json
> +    "checkver": {
```suggestion
    "persist": "switcheroo.settings",
    "checkver": {
```

2020-10-30 08:33 UTC, Ash258 commented on bucket/switcheroo.json
> +    "bin": "switcheroo.exe",
```suggestion
    "pre_install": "if (!(Test-Path \"$persist_dir\\switcheroo.settings\")) { New-Item \"$dir\\switcheroo.settings\" | Out-Null }",
```

2020-10-30 08:33 UTC, Ash258 commented on bucket/switcheroo.json
> +            "switcheroo"
```suggestion
            "Switcheroo"
```

2020-11-03 17:43 UTC, Ash258 commented
/verify

2020-11-03 17:46 UTC, Ash258 reviewed
I would maybe remove the checkver and autoupdate since the repo is dead and PowerToys are released.

2021-12-31 19:53 UTC, rashil2000 commented
https://github.com/ScoopInstaller/Extras/commit/db2dba37be6cf95981e277a2087eb7edf0d1cc69

2021-12-31 19:53 UTC, closed without merging