macrocreator: Add version 5.3.2
ScoopInstaller/Extras pull request #5012
Opened 2020-10-30 01:52 UTC by snowman

2020-10-30 06:43 UTC, Ash258 requested changes

2020-10-30 06:43 UTC, Ash258 commented on bucket/macrocreator.json
> +    "license": {
Do not use URL for valid SPDX identifiers

2020-10-30 09:06 UTC, Ash258 requested changes

2020-10-30 09:06 UTC, Ash258 commented on bucket/macrocreator.json
> +    "shortcuts": [
https://github.com/Pulover/PuloversMacroCreator/blob/master/MacroCreator.ahk#L152-L154

```suggestion
    "pre_install": "Copy-Item \"$persist_dir\\*\" \"$dir\" -Include 'UserEmailAccounts.ini', 'UserGlobalVars.ini' -ErrorAction SilentlyContinue",
    "uninstaller": {
        "script": "Copy-Item \"$dir\\*\" \"$persist_dir\" -Include 'UserEmailAccounts.ini', 'UserGlobalVars.ini' -ErrorAction SilentlyContinue -Force"
    },
    "shortcuts": [
```

2020-11-03 17:58 UTC, Ash258 commented
/verify

2020-11-30 09:44 UTC, wenmin92 commented
/verify

2021-12-30 09:48 UTC, issaclin32 commented
I am merging this without update because
(1) The branch has been deleted
(2) Autoupdate and installation still works fine

We can just wait for automatic updates, and everything will be OK.

2021-12-30 09:48 UTC, merged

2021-12-30 09:50 UTC, rashil2000 commented
The branch still exists - https://github.com/follow-the-vine-to-get-to-the-melon/scoop-extras/tree/MacroCreator

2021-12-30 09:54 UTC, issaclin32 commented
> The branch still exists - https://github.com/follow-the-vine-to-get-to-the-melon/scoop-extras/tree/MacroCreator

Oops. I was wrong. I thought it was deleted when I found that I cannot edit the file.

2021-12-30 09:56 UTC, rashil2000 commented
Check back in 2 hours, Excavator will have run by then.

2021-12-30 10:16 UTC, snowman commented
Thanks , I delete the `MacroCreator` branch now, in case you want to take over

2021-12-30 10:21 UTC, issaclin32 commented
> I would help out if you want, but now I restored deleted `MacroCreator` branch

You can delete the branch now, because it is no longer needed when the PR is merged.

2021-12-30 13:22 UTC, rashil2000 commented
![image](https://user-images.githubusercontent.com/46838874/147755741-71498ff3-b781-46f7-b396-e18ab400cb41.png)

2021-12-30 14:10 UTC, issaclin32 commented
> Excavator failed here
> 
> ![image](https://user-images.githubusercontent.com/46838874/147755741-71498ff3-b781-46f7-b396-e18ab400cb41.png)

Thanks for the follow up.
Still not sure why `v$version` turns into `v1.1.1` 😕 
```
"autoupdate": {
        "url": "https://github.com/Pulover/PuloversMacroCreator/releases/download/v$version/PuloversMacroCreator-Portable.zip"
    }
```

2021-12-30 14:14 UTC, rashil2000 commented
Locally it seems to running fine:

![image](https://user-images.githubusercontent.com/46838874/147759601-43a50672-26b3-417a-af1d-b789a73ca2e0.png)

2021-12-31 05:18 UTC, issaclin32 commented
Looks like there is a bug in the *Excavator*, which turns all new versions into `1.1.1`.

```
acrocreator: 5.4.1 (scoop version is 5.3.2) autoupdate available
Autoupdating macrocreator
Downloading PuloversMacroCreator-Portable.zip to compute hashes!
The remote server returned an error: (404) Not Found.
URL https://github.com/Pulover/PuloversMacroCreator/releases/download/v1.1.1/PuloversMacroCreator-Portable.zip is not valid
ERROR Could not update macrocreator, hash for PuloversMacroCreator-Portable.zip failed!
mu-editor: 1.1.0 (scoop version is 1.0.3)
kid3: 3.9.0 (scoop version is 3.8.7) autoupdate available
Autoupdating kid3
Could not find hash in https://sourceforge.net/projects/kid3/files/kid3/1.1.1
Downloading kid3-1.1.1-win32.zip to compute hashes!
The remote server returned an error: (404) Not Found.
URL https://downloads.sourceforge.net/project/kid3/kid3/1.1.1/kid3-1.1.1-win32.zip is not valid
ERROR Could not update kid3, hash for kid3-1.1.1-win32.zip failed!
languagetool-java: 5.6 (scoop version is 5.5) autoupdate available
Autoupdating languagetool-java
Downloading LanguageTool-1.1.1.zip to compute hashes!
The remote server returned an error: (404) Not Found.
URL https://languagetool.org/download/LanguageTool-1.1.1.zip is not valid
ERROR Could not update languagetool-java, hash for LanguageTool-1.1.1.zip failed!
nswagstudio: couldn't match 'NSwag v([\d.]+)\s*\(Build\s*(\d+)\)' in https://api.github.com/repos/RicoSuter/NSwag/releases/latest
mupdf: couldn't match 'mupdf-([\w.-]+)-windows\.zip' in https://www.mupdf.com/downloads/index.html
nexus-repository-oss: 3.37.3-02 (scoop version is 3.37.0-01) autoupdate available
Autoupdating nexus-repository-oss
Searching hash for nexus-1.1.1-win64.zip in https://download.sonatype.com/nexus/1/nexus-1.1.1-win64.zip.sha1
The remote server returned an error: (404) Not Found.
URL https://download.sonatype.com/nexus/1/nexus-1.1.1-win64.zip.sha1 is not valid
Could not find hash in https://download.sonatype.com/nexus/1/nexus-1.1.1-win64.zip.sha1
Downloading nexus-1.1.1-win64.zip to compute hashes!
The remote server returned an error: (404) Not Found.
```

2021-12-31 07:15 UTC, rashil2000 commented
That's pretty weird!

The only change done to checkver.ps1 in past few days is this:

![image](https://user-images.githubusercontent.com/46838874/147809205-303c07fa-b1f8-4e9d-bee1-7c9c5e56e239.png)

But it's not causing any problems in Main or Versions...