dxwnd: Add version 2_05_58
ScoopInstaller/Extras pull request #5015
Opened 2020-10-30 06:58 UTC by snowman

2020-10-30 07:07 UTC, Ash258 requested changes
The version does not use underscore

![image](https://user-images.githubusercontent.com/13260377/97670645-fac3ae00-1a86-11eb-9e0e-82b90e9893cf.png)

2020-10-30 07:07 UTC, Ash258 commented on bucket/dxwnd.json
> +    "pre_install": [
Do not use array for one string

2020-10-30 07:07 UTC, Ash258 commented on bucket/dxwnd.json
> +    "license": "GPL-3.0-or-later",
version
description
homepage
license

2020-10-30 07:55 UTC, Ash258 requested changes

2020-10-30 07:55 UTC, Ash258 commented on bucket/dxwnd.json
> +    "checkver": "v([\\d_]+)_build.rar",
You are matching underscore, but the versioning is using dots.

2020-11-03 17:38 UTC, Ash258 requested changes
What is `winmm.ini` and `tweaks.ini`?

2021-12-30 08:06 UTC, issaclin32 commented
superseded by #7629

2021-12-30 08:06 UTC, closed without merging