add qtscrcpy
ScoopInstaller/Extras pull request #5020
Opened 2020-10-30 10:44 UTC by Rehtt

2020-10-30 10:49 UTC, Ash258 requested changes
HOw is this different from https://github.com/ScoopInstaller/Main/blob/master/bucket/scrcpy.json??

2020-10-30 10:49 UTC, Ash258 commented on bucket/qtscrcpy.json
> +    "license":"Apache Licence 2.0",
Invalid SPDX identifier

2020-10-30 10:49 UTC, Ash258 commented on bucket/qtscrcpy.json
> +            "extract_dir":"QtScrcpy-win-x86-v1.4.5"
Missing hashes

2020-10-30 10:49 UTC, Ash258 commented on bucket/qtscrcpy.json
> +    },
simplify `checkver: github`

2020-10-30 10:49 UTC, Ash258 commented on bucket/qtscrcpy.json
> +        }
missing architecture

2020-10-30 10:49 UTC, Ash258 commented on bucket/qtscrcpy.json
> +    "description": "QtScrcpy connects to Android devices via USB (or via TCP/IP) for display and control. It does NOT require the root privileges",
do not mention application name in description

2020-10-30 12:05 UTC, Rehtt commented
The difference between QtScrcpy and the original scrcpy is as follows:

keys|scrcpy|QtScrcpy
--|:--:|:--:
ui|sdl|qt
video encode|ffmpeg|ffmpeg
video render|sdl|opengl
cross-platform|self implemented|provided by Qt
language|C|C++
style|sync|async
keymap|no custom keymap|support custom keymap
build|meson+gradle|Qt Creator

2020-10-30 12:37 UTC, Ash258 requested changes
Execute checkver and push the formated manifest

2020-10-30 12:37 UTC, Ash258 commented on bucket/qtscrcpy.json
> +
There is no such file in the releases

2020-10-30 12:37 UTC, Ash258 commented on bucket/qtscrcpy.json
> +            "hash": "c6806f188ca21bd7ead9519eacd3b15eef5df6fb9d9dd5766ba74310a4b4cc25"
Hashes before extract_dir

2020-11-03 18:12 UTC, Ash258 requested changes
Should be `config` folder persisted? What everything is stored there?

![A](https://i.imgur.com/OUgFvod.png)

2020-11-03 18:12 UTC, Ash258 commented on bucket/qtscrcpy.json
> +    "description": "Connects to Android devices via USB (or via TCP/IP) for display and control.",
```suggestion
    "description": "Display and control Android device via TCP/IP or USB",
```

2020-11-13 10:42 UTC, Rehtt commented
No need to keep the `config` folder

2020-11-14 08:44 UTC, Ash258 commented
... ![A](https://i.imgur.com/QqiM5Kl.png)

2020-11-17 02:26 UTC, Rehtt commented
Oh, that's a user profile, I rarely use it so I forgot

2021-01-05 10:25 UTC, 7wells commented
Hello, is somebody still working on this?

A happy New Year to all of you!

2021-12-30 10:21 UTC, rashil2000 commented
/verify

2021-12-30 10:22 UTC, merged