add shadowsocks v2ray plugin
ScoopInstaller/Extras pull request #5064
Opened 2020-11-06 03:35 UTC by g5li

The very useful [v2ray plugin for shadowsocks](https://github.com/shadowsocks/v2ray-plugin).

Manually tested.

2020-11-06 06:16 UTC, Ash258 requested changes

2020-11-06 06:16 UTC, Ash258 commented on bucket/shadowsocks-v2ray-plugin.json
> +            "regex": "([.*])[\\s]+$basename"
Go with something liek this:

```json
            "regex": "$sha1\\s+bin/$basename"
```

2020-11-06 06:16 UTC, Ash258 commented on bucket/shadowsocks-v2ray-plugin.json
> +            ]
Completely nonsense name.

```suggestion
            "bin": [
                [
                    "v2ray-plugin_windows_386.exe",
                    "shadowsocks-v2ray-plugin"
                ]
            ]
```

2020-11-06 06:16 UTC, Ash258 commented on bucket/shadowsocks-v2ray-plugin.json
> +            ]
```suggestion
            "bin": [
                [
                    "v2ray-plugin_windows_amd64.exe",
                    "shadowsocks-v2ray-plugin"
                ]
            ]
```

2020-11-06 06:16 UTC, Ash258 commented on bucket/shadowsocks-v2ray-plugin.json
> +    "description": "Yet another SIP003 plugin for shadowsocks, based on v2ray",
```suggestion
    "description": "SIP003 plugin based on v2ray for shadowsocks",
```

2020-11-10 21:41 UTC, Ash258 commented
/verify

2020-11-10 21:42 UTC, Ash258 reviewed
Manifest is OK. But i cannot verify functionality

2021-12-30 05:00 UTC, issaclin32 approved these changes

2021-12-30 05:00 UTC, merged