Add RoslynPad
ScoopInstaller/Extras pull request #5094
Opened 2020-11-11 22:00 UTC by gregmac

> A cross-platform C# editor based on Roslyn and AvalonEdit

- https://roslynpad.net/ 
- https://github.com/aelij/RoslynPad

2020-11-12 00:40 UTC, gregmac commented
@Ash258 You tagged this with `package-fix-needed` -- Is a change needed here, and if so, what?

2020-11-12 06:26 UTC, Ash258 requested changes
Why all of of you are so impatient and cannot wait a few hours? Do you really think everyone has time to do review immediately you open PR??

![A](https://i.imgur.com/cs2pdbC.png)

2020-11-12 06:26 UTC, Ash258 commented on bucket/roslynpad.json
> +    "url": "https://github.com/aelij/RoslynPad/releases/download/15.1/RoslynPad.zip",
```suggestion
    "suggest": {
        "dotnetRuntime": "windowsdesktop-runtime"
    },
    "architecture": {
        "64bit": {
            "url": "https://github.com/aelij/RoslynPad/releases/download/15.1/RoslynPad.zip",
            "hash": "9d2f38a97bfc34b2918439b6265edec5460d9f86346b15d158d1c0f7d9cd3645"
        }
    },
```

2020-11-12 06:26 UTC, Ash258 commented on bucket/roslynpad.json
> +    "homepage": "https://roslynpad.net/",
```suggestion
    "homepage": "https://roslynpad.net",
```

2020-11-12 06:26 UTC, Ash258 commented on bucket/roslynpad.json
> +        "url": "https://github.com/aelij/RoslynPad/releases/download/$version/RoslynPad.zip"
```suggestion
        "architecture": {
            "64bit": {
                "url": "https://github.com/aelij/RoslynPad/releases/download/$version/RoslynPad.zip"
            }
        }
```

2020-11-17 07:44 UTC, Ash258 commented
What does this mean? The very first thing on application startup

![A](https://i.imgur.com/RRl4eLm.png)

2021-12-30 04:59 UTC, issaclin32 commented
Works fine for me.
![未命名 - 16](https://user-images.githubusercontent.com/27724471/147722919-7ac8eb83-ee7c-41d8-afb7-edbf455226a7.png)

2021-12-30 04:59 UTC, issaclin32 approved these changes

2021-12-30 04:59 UTC, merged