Folding@home: Add version 7.6.21
ScoopInstaller/Extras pull request #5166
Opened 2020-11-23 08:21 UTC by schance995

2020-11-23 08:26 UTC, Ash258 requested changes
https://github.com/lukesampson/scoop-extras/pull/4730/files

2020-11-24 05:59 UTC, schance995 commented
What is the correct way to write multiple licenses in the manifest?

The client is freeware but the control gui is GPL-3: <https://github.com/FoldingAtHome/fah-control>

2020-11-25 08:53 UTC, schance995 commented
Found the relevant information in the [docs](https://github.com/lukesampson/scoop/wiki/App-Manifests#optional-properties).
> If different files have different licenses, separate licenses with a comma (,).

> If there are both open-source and not open-source licenses, please list all non-open source licenses first

2020-11-25 18:02 UTC, Ash258 requested changes
File persising do not work

![A](https://i.imgur.com/VRUyPg3.png)

2020-11-25 18:02 UTC, Ash258 commented on bucket/foldingathome.json
> +        "work",
```suggestion
        "configs",
        "cores",
        "work",
        "logs",
```

2020-11-26 06:21 UTC, Ash258 requested changes
`git mv bucket/foldingathome.json bucket/folding-at-home.json`

2021-12-30 04:44 UTC, issaclin32 approved these changes

2021-12-30 04:44 UTC, merged