add foldit
ScoopInstaller/Extras pull request #5172
Opened 2020-11-24 08:08 UTC by schance995

<https://fold.it/portal/info/about>

"Foldit is a revolutionary crowdsourcing computer game enabling *you* to contribute to important scientific research. "

The installer on their website is not the latest, running it the first time automatically updates it. That's why I put a version number of 1.

2020-11-25 19:00 UTC, Ash258 requested changes

2020-11-25 19:00 UTC, Ash258 commented on bucket/foldit.json
> +    "post_install": "Remove-Item \"$dir\\uninstall.exe\"",
```suggestion
    "version": "nightly",
    "description": "Crowdsourcing computer game contributing to important scientific research",
    "homepage": "https://fold.it",
    "license": {
        "identifier": "Freeware",
        "url": "https://fold.it/portal/legal"
    },
    "url": "https://files.ipd.uw.edu/pub/foldit/Foldit-win_x86.exe#/dl.7z",
    "pre_install": "Remove-Item \"$dir\\`$*\", \"$dir\\uninst*\" -Recurse",
    "bin": "Foldit.exe",
```

2020-11-26 06:23 UTC, Ash258 requested changes
Find a way how to manually persist all themes, configs, GPUs, and cmp-* folders

2020-11-29 07:01 UTC, schance995 commented
This is my persist list so far:
```
"persist": [
    "cmp-binary-00000000000000000000000000000000/",
    "cmp-resources-00000000000000000000000000000000/",
    "theme.txt",
    "hotkeys.txt",
    "log.txt",
    "options.txt",
    "mlog"
]
```

But there are some issues, any tips on how to solve these would be helpful.
1. it looks like cmp-* number is dependent on latest version which is not available on install.
2. All of these files except for cmp 0s do not exist until after the app is first run. If I persist these I get folders instead. Easiest way to check is to open log.txt to read the update progress on first run, it doesn't work with persistence.
![cannot persist foldit files](https://user-images.githubusercontent.com/54919210/100535427-cdcdfc80-31e6-11eb-82bd-2790021fa446.png)

2023-03-17 12:04 UTC, jasongodev commented
@schance995 What's the progress of this PR?

2023-03-18 21:32 UTC, jasongodev commented
> I haven't played with FoldIt in a while, feel free to continue this patch.

I'm proposing to close this PR until such time it is ready or there's a lot of people requesting it in the future.

2023-04-15 15:59 UTC, closed without merging