ubports-installer: Add version 0.7.4
ScoopInstaller/Extras pull request #5199
Opened 2020-11-27 04:53 UTC by schance995

Has not yet been tested for persistent data and expected functionality.

2020-11-27 18:08 UTC, Ash258 requested changes

2020-11-27 18:08 UTC, Ash258 commented on bucket/ubports-installer.json
> +        }
```suggestion
    "version": "0.7.4-beta",
    "description": "A friendly cross-platform Installer for Ubuntu Touch",
    "homepage": "https://ubuntu-touch.io//ubuntu-touch.io",
    "license": "GPL-3.0-only",
    "suggest": {
        "adb": "adb"
    },
    "architecture": {
        "64bit": {
            "url": "https://github.com/ubports/ubports-installer/releases/download/0.7.4-beta/ubports-installer_0.7.4-beta_win.exe#/dl.7z",
            "hash": "ec347f98c02ec0b9a339e5c1d35b35da6de8f79509a1f8c065ecff037008e747",
            "pre_install": [
                "Expand-7zipArchive \"$dir\\`$PLUGINSDIR\\app-64.7z\" \"$dir\"",
                "Remove-Item \"$dir\\`$*\" -Recurse"
            ]
        }
    },
    "shortcuts": [
        [
            "ubports-installer.exe",
            "UBports Installer"
        ]
    ],
    "checkver": {
        "url": "https://github.com/ubports/ubports-installer/releases/latest",
        "regex": "ubports-installer_([\\w.-]+)_win\\.exe"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/ubports/ubports-installer/releases/download/$version/ubports-installer_$version_win.exe#/dl.7z",
                "hash": {
                    "url": "$baseurl/ubports-installer_$version_win.exe.sha256"
                }
            }
        }
```

2020-12-03 15:25 UTC, Ash258 commented
/verify

2020-12-03 15:26 UTC, Ash258 reviewed
Manifest and installation is fine, but I cannot fully test the application

2020-12-03 23:19 UTC, NeoTheThird commented
> doesn't look like there is persistent data

Upstream maintainer here. There is persistent data in `%APPDATA%`, but if it doesn't persist, that's okay. You'll just have to re-download files on every start.

2021-12-30 09:18 UTC, issaclin32 commented
> > doesn't look like there is persistent data
> 
> Upstream maintainer here. There is persistent data in `%APPDATA%`, but if it doesn't persist, that's okay. You'll just have to re-download files on every start.

Thanks for the info. I will use **Junctions** to keep the data (when user updates the app with Scoop)

2021-12-30 09:22 UTC, issaclin32 commented
Superseded by #7630.

2021-12-30 09:22 UTC, closed without merging