revouninstaller: Add version 2.2.0
ScoopInstaller/Extras pull request #5205
Opened 2020-11-27 22:38 UTC by schance995

See <https://github.com/lukesampson/scoop-extras/pull/562#issuecomment-636460531>.
Removed UAC registry evasion as it's not required for the app to function. Autoupdate reuses download link so the version # is properly updated.

2020-12-03 15:38 UTC, Ash258 requested changes

2020-12-03 15:38 UTC, Ash258 commented on bucket/revouninstaller.json
> +    "version": "2.2.0",
```suggestion
    "version": "2.2.0",
    "description": "Software uninstaller with support for additional cleanup of registries/files",
    "homepage": "https://www.revouninstaller.com/products/revo-uninstaller-free/",
    "license": "Freeware",
```

2020-12-03 15:38 UTC, Ash258 commented on bucket/revouninstaller.json
> +    },
```suggestion
    "checkver": "Version: ([\\d.]+)",
```

2020-12-03 15:38 UTC, Ash258 commented on bucket/revouninstaller.json
> +    ],
```suggestion
    "shortcuts": [
        [
            "RevoUPort.exe",
            "Revo Uninstaller"
        ]
    ],
```

2020-12-03 15:38 UTC, Ash258 commented on bucket/revouninstaller.json
> +    "url": "https://www.revouninstaller.com/download-free-portable.php#/dl.zip",
```suggestion
    "url": "https://www.revouninstaller.com/download-free-portable.php#/dl.zip",
    "hash": "f543d9e0627f4170674310f5759498bc65a08446c3c2693f9771493c9d3063f5",
```

2020-12-03 15:39 UTC, Ash258 requested changes
- Persist dat files and settings
- Disable autoudpate

![image](https://user-images.githubusercontent.com/13260377/101051758-1d654d00-3586-11eb-84fe-3b768f65e65f.png)

2020-12-03 20:24 UTC, schance995 commented
Config files are written after first run of app, I think best thing to do is notify user. Feel free to edit the notes if they are too long.

2020-12-03 20:27 UTC, Ash258 requested changes

2020-12-03 20:27 UTC, Ash258 commented on bucket/revouninstaller.json
> +    "post_install": "(Get-Content \"$dir\\settings.ini\") -replace 'AU on startup=1','AU on startup=0' | Set-Content \"$dir\\settings.ini\"",
Why post?

2020-12-03 20:27 UTC, Ash258 commented on bucket/revouninstaller.json
> +    "post_install": "(Get-Content \"$dir\\settings.ini\") -replace 'AU on startup=1','AU on startup=0' | Set-Content \"$dir\\settings.ini\"",
- pre_install everything
- Do this: `'file1', 'file2' | ForEach-Object { if (!....) { new-item } }`

2020-12-03 20:27 UTC, Ash258 commented on bucket/revouninstaller.json
> +        "settings.ini"
sort

2020-12-03 20:27 UTC, Ash258 commented on bucket/revouninstaller.json
> +    ]
Notes are essential information to user. It needs to be at top of manifest, after license

2020-12-03 20:27 UTC, Ash258 commented on bucket/revouninstaller.json
> +        "Then it is highly recommended to disable autoupdate in the app (Options -> Disable autoupdate), or in settings.ini"
Completely nonse to user as it will be disable automatically.

2020-12-03 20:27 UTC, Ash258 commented on bucket/revouninstaller.json
> +        "The first time you run the app, close it right away so the app can create config files.",
What??

2020-12-03 20:27 UTC, schance995 commented
Persist files are created on first run of app. I tried editing autoupdate on install but it won't work without writing the whole `settings.ini`. I think the best thing to do is to notify user about autoupdate.

2020-12-03 20:42 UTC, schance995 commented
I see I misinterpreted autoupdate, apologies.

2020-12-03 20:44 UTC, Ash258 requested changes

2020-12-03 20:44 UTC, Ash258 commented on bucket/revouninstaller.json
> +        "        Write-Host 'File' $_ 'does not exists. Creating.' -f Yellow",
```suggestion
```

2020-12-03 20:44 UTC, Ash258 commented on bucket/revouninstaller.json
> +        "        Set-Content \"$dir\\$_\" $content -Encoding Ascii",
There is no $content.

Use New-Item

2020-12-03 20:44 UTC, Ash258 commented on bucket/revouninstaller.json
> +        "(Get-Content \"$dir\\settings.ini\") -replace 'AU on startup=1','AU on startup=0' | Set-Content \"$dir\\settings.ini\""
DRY.

- Just save the AU into regex capture group and then reference it in replace
- Always use encoding ascii in set-content

2021-11-10 05:49 UTC, pratikpc commented
Closing as schance995:revouninstaller has been deleted.

2021-11-10 05:49 UTC, closed without merging