Initial commit for Portfolio Performance app
ScoopInstaller/Extras pull request #5388
Opened 2020-12-29 22:12 UTC by GotAnAccount

2020-12-29 22:21 UTC, GotAnAccount commented
any chance you could point to where I could find what fix is needed? is there a check list I missed?

2020-12-31 16:43 UTC, Ash258 requested changes

2020-12-31 16:43 UTC, Ash258 commented on bucket/portfolio-performance.json
> +    ]
```suggestion
    "version": "0.49.4",
    "description": "Investment portfolio performance calculator",
    "homepage": "https://www.portfolio-performance.info/en/",
    "license": "EPL-1.0 License",
    "suggest": {
        "JDK": [
            "java/oraclejdk",
            "java/openjdk"
        ]
    },
    "architecture": {
        "64bit": {
            "url": "https://github.com/buchen/portfolio/releases/download/0.49.4/PortfolioPerformance-0.49.4-win32.win32.x86_64.zip",
            "hash": "b6159cc003b6e6710715e4b0664945075803c8357a3e90f74db2c3a7dcec6ae3"
        }
    },
    "extract_dir": "portfolio",
    "shortcuts": [
        [
            "PortfolioPerformance.exe",
            "Portfolio Performance"
        ]
    ],
    "checkver": ">Download\\s+([\\d.]+)</",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/buchen/portfolio/releases/download/$version/PortfolioPerformance-$version-win32.win32.x86_64.zip"
            }
        }
    }
```

2021-01-20 18:12 UTC, rasa commented
/verify

2021-10-30 20:04 UTC, pratikpc commented on bucket/portfolio-performance.json
> +    "license": "EPL-1.0 License",
SPDX is EPL-1.0

2021-10-30 20:06 UTC, pratikpc commented on bucket/portfolio-performance.json
> +}
We need checkver and autoupdate as well

checkver: "github" would work IMHO

2022-01-01 19:30 UTC, rashil2000 commented
/verify

2022-01-01 19:34 UTC, merged