Update to version 1.4.3
ScoopInstaller/Extras pull request #5881
Opened 2021-03-21 02:18 UTC by b-palaniappan

Update robo3t to version 1.4.3

2021-03-28 15:11 UTC, Ash258 requested changes
Do not work. Database is up and running, but robo3t do not do anything after connection

![image](https://user-images.githubusercontent.com/13260377/112757098-89ae0580-8fe8-11eb-9eb7-8bde415cd65a.png)

2021-03-28 15:11 UTC, Ash258 commented on bucket/robo3t.json
> +            "extract_dir": "robo3t-1.4.3-windows-x86_64-48f7dfd"
```suggestion
            "hash": "15c0d1d5751d68023fcca0f9e0db14dc69ea4607c2a4c9645df10b380c1653dd",
            "extract_dir": "robo3t-1.4.3-windows-x86_64-48f7dfde"
```

2021-03-28 16:13 UTC, b-palaniappan commented
Able to test with my local mongo on Docker.
![image](https://user-images.githubusercontent.com/26579908/112758975-9c0f4b80-8fb6-11eb-84d6-ed963b1dd829.png)

2021-04-01 08:43 UTC, pratikpc commented
@b-palaniappan Robo3T seems to now [release](https://github.com/Studio3T/robomongo/releases/latest) via [GitHub](https://github.com/Studio3T/robomongo)

Could you update checkver to use GitHub?
 checkver: github
And switch the download link to the GitHub ones?

2021-10-30 15:07 UTC, igitur commented
> @b-palaniappan Robo3T seems to now [release](https://github.com/Studio3T/robomongo/releases/latest) via [GitHub](https://github.com/Studio3T/robomongo)
> 
> Could you update checkver to use GitHub? checkver: github And switch the download link to the GitHub ones?

Fixed in https://github.com/ScoopInstaller/Extras/pull/7196

2021-10-30 15:31 UTC, pratikpc commented on bucket/robo3t.json
>      }
@b-palaniappan You would need extract DIR here also

2021-10-30 15:32 UTC, pratikpc commented on bucket/robo3t.json
> -            "url": "https://download.studio3t.com/robomongo/windows/robo3t-1.4.2-windows-x86_64-8650949.zip",
Unless the tool is 32 bit only, for new updates we prefer retaining architecture and 64bit for 64bit apps to minimize inconvenience for 32 bit users

So please use the old format

2021-10-30 15:32 UTC, pratikpc commented on bucket/robo3t.json
> -        "architecture": {
Unless the tool is 32 bit only, for new updates we prefer retaining architecture and 64bit for 64bit apps to minimize inconvenience for 32 bit users

So please use the old format

But newer GitHub URLs should be obviously retained

2021-10-30 15:33 UTC, pratikpc commented
@igitur we would prefer if you continue to contribute to this specific PR and assist @b-palaniappan instead of creating a new one

2021-10-30 15:57 UTC, igitur commented
> @igitur we would prefer if you continue to contribute to this specific PR and assist @b-palaniappan instead of creating a new one

The remote repo for this PR has been deleted. It's really much easier to close this PR and continue on #7196 .

2021-10-30 15:59 UTC, closed without merging