add clash.net 1.0.1
ScoopInstaller/Extras pull request #6126
Opened 2021-04-28 12:08 UTC by lifansama

A Clash GUI Proxy For Windows Based On .NET 5

> scoop install clash.net
Installing 'clash.net' (1.0.1) [64bit]
Loading Clash.NET.1.0.1.x64.7z from cache
Checking hash of Clash.NET.1.0.1.x64.7z ... ok.
Extracting Clash.NET.1.0.1.x64.7z ... done.
Linking ~\scoop\apps\clash.net\current => ~\scoop\apps\clash.net\1.0.1
Creating shortcut for Clash.NET (ClashDotNet.exe)
'clash.net' (1.0.1) was installed successfully!

2021-04-28 12:32 UTC, Ash258 requested changes
- Add autoupdate with hash extraction from `checksum` file on releases page
- Enable portable mode and add persist for all relevant files/directories

![image](https://user-images.githubusercontent.com/13260377/116403445-daa25b00-a82d-11eb-8db8-885a008af706.png)

2021-04-28 12:32 UTC, Ash258 commented on bucket/clash.net.json
> +    "license": "none",
```suggestion
    "license": "Unknown",
```

2021-04-28 12:32 UTC, Ash258 commented on bucket/clash.net.json
> +    "description": "A Clash GUI Proxy For Windows Based On .NET 5",
Keeping `For Windows` and dotnet version is not needed. 

Scoop is only for windows and version of dotnet is not relevant

2021-04-28 12:32 UTC, Ash258 commented on bucket/clash.net.json
> +    "architecture": {
Add suggest for `windowsdesktop-runtime`

2021-11-25 16:47 UTC, issaclin32 commented
The software is discontinued and removed by the developer.
https://github.com/ClashDotNetFramework/ClashDotNetFramework

2021-11-25 16:47 UTC, closed without merging