Create imdone.json
ScoopInstaller/Extras pull request #6156
Opened 2021-05-02 12:31 UTC by telenieko

Simple and powerful kanban board built on top of plain text markdown files or code.

Regarding the criteria for inclussion in the main bucket: this is not a developer tool, and it is GUI based which excludes it from main.

Hence, because the first criteria is not met, this is proposed for inclusion in extras.

The project does not publish hashes, if this is an absolute requirement for inclusion into extras please say so I can open an issue there.

Licensing is not clear, yet,  PR kept as draft until https://github.com/imdone/imdone/issues/109 is closed.

2021-05-21 10:39 UTC, telenieko commented
The license has been confirmed as propietary.

2021-05-21 11:09 UTC, Ash258 commented
Proprietary means nothing when there is no license agreement, which user has to accept. Until there is no URL with the license file it is useless.

2021-05-21 11:16 UTC, telenieko commented
> Proprietary means nothing when there is no license agreement, which user has to accept. Until there is no URL with the license file it is useless.

Shall I write "Unknown" like in https://github.com/lukesampson/scoop-extras/blob/master/bucket/7tt.json ?

2021-12-27 16:25 UTC, rashil2000 requested changes
Modify the manifest according to the order of the fields here - https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md

Also, does `imdone.exe` binary take any commandline arguments?

2021-12-27 16:25 UTC, rashil2000 commented on bucket/imdone.json
> +        "identifier": "Unknown",
```suggestion
        "identifier": "Proprietary",
```

2022-01-08 14:57 UTC, rashil2000 commented
@issaclin32 could you please have a go at it?

2022-01-09 06:42 UTC, issaclin32 commented
> @issaclin32 could you please have a go at it?

The manifest works fine.
*Persist* is not needed because config file is at `$Env:AppData\imdone`.

I am okay with adding this. It is up to your choice.

2022-01-09 06:48 UTC, rashil2000 commented
> I am okay with adding this. It is up to your choice.

I'm okay with this too 👍

> ![image](https://user-images.githubusercontent.com/46838874/147838589-2180857e-3968-4423-b68e-7a321c28872b.png)
> 
> * They have a portable release too. Use that.
> * Modify the manifest according to the order of the fields here - https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md
> * Remove `bin` field

Is the portable release functional?

2022-01-09 08:14 UTC, issaclin32 commented
/verify

2022-01-09 08:18 UTC, issaclin32 commented
> Is the portable release functional?

Yep. It works totally fine. Also the config file location is the same. I think the only difference is that portable version will not register itself in "installed programs".

2022-01-09 08:18 UTC, issaclin32 approved these changes

2022-01-09 08:47 UTC, merged

2022-01-09 08:47 UTC, rashil2000 commented
Great, thanks so much!