add suanpan v1.4
ScoopInstaller/Extras pull request #6249
Opened 2021-05-25 23:28 UTC by TLCFEM

2021-05-25 23:32 UTC, TLCFEM commented
/verify

2021-05-26 04:42 UTC, Ash258 requested changes

2021-05-26 04:42 UTC, Ash258 commented on bucket/suanpan.json
> +        "regex": "suanPan-v([0-9]\\.[0-9]\\.?[0-9]?)"
```suggestion
        "github": "https://github.com/TLCFEM/suanPan",
        "regex": "download/suanPan-v([\\d.]+)/"
```

2021-05-26 04:42 UTC, Ash258 commented on bucket/suanpan.json
> +    },
```suggestion
    "version": "1.5",
    "homepage": "https://tlcfem.github.io/suanPan/",
    "description": "Parallel and heterogeneous finite element analysis framework",
    "license": "GPL-3.0-only",
    "notes": "You can run \"$dir\\AddAssociation.bat\" to configure file association and Sublime Text syntax support.",
    "suggest": {
        "vcredist2019": "vcredist2019"
    },
    "architecture": {
        "64bit": {
            "url": "https://github.com/TLCFEM/suanPan/releases/download/suanPan-v1.5/suanPan-win-mkl-vtk.zip",
            "hash": "de9f1f1ed3d3d9c92e5c3c875cd22c028ea73b4426c08cc5797f4417a8d16cb5"
        }
    },
    "bin": "suanPan.exe",
```

2021-05-26 04:42 UTC, Ash258 commented on bucket/suanpan.json
> +            "url": "https://github.com/TLCFEM/suanPan/releases/download/suanPan-v$version/suanPan-win-mkl-vtk.sha256"
```suggestion
        "architecture": {
            "64bit": {
                "url": "https://github.com/TLCFEM/suanPan/releases/download/suanPan-v$version/suanPan-win-mkl-vtk.zip"
            }
        },
        "hash": {
            "url": "$baseurl/suanPan-win-mkl-vtk.sha256"
```

2021-05-30 18:08 UTC, Ash258 requested changes
Does not work

![image](https://user-images.githubusercontent.com/13260377/120115172-caf69900-c182-11eb-9b80-dd6db3aed3fa.png)

2021-05-30 20:08 UTC, TLCFEM commented
Given that the binary is statically linked, I doubt if that is the problem of vcredist. Do you mind to check if vcredist is the latest version, in case it is not?

2021-05-31 02:16 UTC, TLCFEM commented
I have tested the package with Win10 virtual environment provided by MS [https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/).

The program can be successfully executed after confirming the "Unknown Publisher" warning.
![powershell_PLnhJJSRXP](https://user-images.githubusercontent.com/19872523/120130277-9ed71a00-c17a-11eb-95bc-cdc96b18c394.png)

It can be executed via scoop as well.
![powershell_Jw9fzHxp2P](https://user-images.githubusercontent.com/19872523/120130592-697efc00-c17b-11eb-9870-06dd1ef062de.png)

@Ash258 Please see what to do next.

2021-06-25 03:45 UTC, TLCFEM commented
@Ash258 Another thing is, the program requires AVX.

2021-11-03 10:48 UTC, issaclin32 commented
Already exists in the main bucket (https://github.com/ScoopInstaller/Main/pull/2754)

2021-11-03 10:48 UTC, closed without merging