Add QOwnNotes
ScoopInstaller/Extras pull request #6305
Opened 2021-06-05 12:42 UTC by rdmcgregor

2021-06-06 01:31 UTC, rdmcgregor commented
What needs to be fixed?  Is there something I have missed?

2021-06-06 07:14 UTC, Ash258 requested changes
![image](https://user-images.githubusercontent.com/13260377/120916028-5ef6c200-c6a7-11eb-8400-18183b20badc.png)

2021-06-06 07:14 UTC, Ash258 commented on bucket/qownnotes.json
> +    "description": "",
???

2021-06-06 07:14 UTC, Ash258 commented on bucket/qownnotes.json
> +    "license": "GPL-2.0",
Invalid SPDX identifier

2021-06-06 07:14 UTC, Ash258 commented on bucket/qownnotes.json
> +    "hash": "8BCF6460A1A5DA4F483E8B883D6CC86B82C5C60D568064DC603A3DC5A1E17FD7",
Checkver was not used

2021-06-08 13:27 UTC, rdmcgregor commented on bucket/qownnotes.json
> +    "description": "",
fixed missing description

2021-06-08 13:28 UTC, rdmcgregor commented on bucket/qownnotes.json
> +    "license": "GPL-2.0",
fixed license id

2021-06-08 13:28 UTC, rdmcgregor commented on bucket/qownnotes.json
> +    "hash": "8BCF6460A1A5DA4F483E8B883D6CC86B82C5C60D568064DC603A3DC5A1E17FD7",
fixed

2021-06-08 13:31 UTC, rdmcgregor commented
Updated, didn't use portable option for execution because that doesn't seem like the best choice for executing this app after installing with scoop.

2021-06-08 13:42 UTC, Ash258 requested changes
Use portable mode.

2021-06-11 13:18 UTC, rdmcgregor commented
Migrated to portable mode and ran url and version checks

2021-06-11 13:20 UTC, Ash258 submitted a review, later dismissed

2021-06-11 13:20 UTC, Ash258 commented on bucket/qownnotes.json
> +    ],
Where is persist??

2021-11-19 14:43 UTC, issaclin32 commented
I updated the manifest by myself because this PR hasn't been updated for a while.

2021-11-19 15:12 UTC, rashil2000 commented
/verify

2021-11-19 15:13 UTC, rashil2000 approved these changes

2021-11-19 17:39 UTC, merged