altserver: Add version 1.4.6
ScoopInstaller/Extras pull request #6556
Opened 2021-08-03 15:11 UTC by Phantop

AltServer is a tool allowing for the sideloading of apps on iOS devices. Solves issue #6394. The latest version is currently untagged in the GitHub repository for whatever reason, however the release is noted in the `develop` branch (and the version installed is 1.4.6 according to the about dialog.

2021-08-03 15:39 UTC, Ash258 requested changes
It is beta.

Come after it goes stable 

![image](https://user-images.githubusercontent.com/13260377/128044754-f3af88a0-620d-4f7b-a13b-59e689753094.png)

2021-08-03 15:39 UTC, Ash258 commented on bucket/altserver.json
> +    "installer": {
installer is irrelevant. Use `pre_install`

2021-08-03 15:39 UTC, Ash258 commented on bucket/altserver.json
> +    "notes": [
Notes at the end of manifest are uselesss

2021-08-03 15:39 UTC, Ash258 commented on bucket/altserver.json
> +    "license": "AGPL-3.0",
Invalid SPDX license identifier

2021-08-03 15:39 UTC, Ash258 commented on bucket/altserver.json
> +    "description": "A home for apps that push the boundaries of iOS. No jailbreak required.",
Completely nonsense, marketing description, which does not help end user

2021-08-03 16:23 UTC, Phantop commented
> It is beta.
> 
> Come after it goes stable
> 
> ![image](https://user-images.githubusercontent.com/13260377/128044754-f3af88a0-620d-4f7b-a13b-59e689753094.png)

A quick search shows that there are a few pieces of beta software in this bucket. Would renaming this to altserver-beta potentially change whether it could be accepted?

2021-12-09 10:39 UTC, issaclin32 commented
I think it is okay to add this package.
However I cannot find reliable release notes that matches the correct version.
Will try to solve it using [UpdateTracker](https://github.com/ScoopInstaller/UpdateTracker).

2022-01-03 16:31 UTC, rashil2000 commented
@issaclin32 I'm closing this PR as the file is not editable (remote deleted). However the package request is still open to keep track of this.

2022-01-03 16:31 UTC, closed without merging