Add roundedtb: R2.2
ScoopInstaller/Extras pull request #6574
Opened 2021-08-06 22:01 UTC by NoraTheGamer

2021-08-08 13:30 UTC, Ash258 requested changes

2021-08-08 13:30 UTC, Ash258 commented on bucket/roundedtb.json
> +        "github": "https://github.com/torchgm/RoundedTB"
Cannot work...

2021-08-08 13:30 UTC, Ash258 commented on bucket/roundedtb.json
> +    "license": "GPL-3.0-only",
No description

2021-08-08 13:30 UTC, Ash258 commented on bucket/roundedtb.json
> +    "version": "R2.2",
Why there is `R`??

2021-08-08 13:30 UTC, Ash258 commented on bucket/roundedtb.json
> +    ],
Irrelevant. User should be prompted by application.

```suggestion
```

2021-08-08 13:30 UTC, Ash258 commented on bucket/roundedtb.json
> +    },
Does not make sense. Uninstallation will be stopped if the executable is running

```suggestion
```

2021-08-15 12:48 UTC, UnicorNora commented on bucket/roundedtb.json
> +    "version": "R2.2",
Thats the tag on github

2021-08-15 12:48 UTC, UnicorNora commented on bucket/roundedtb.json
> +        "github": "https://github.com/torchgm/RoundedTB"
Why not

2021-12-29 10:51 UTC, rashil2000 commented
/verify

2021-12-29 10:56 UTC, merged