foxit-reader: Update to version 11.0.1.49938
ScoopInstaller/Extras pull request #6584
Opened 2021-08-08 12:23 UTC by gitolicious

Foxit has renamed most of their products, see https://www.foxit.com/.

> Foxit has changed some product names. To learn more click here.

"Foxit Reader" is now called "Foxit PDF Reader". How are changes like this handled usually?
- create a separate manifest `foxit-pdf-reader.json`
- rename the manifest file
- just keep using the old manifest

2021-08-08 12:29 UTC, Ash258 requested changes
1. Revert everything that you have done
2. Add `"note": "Deprecated. Use extras/foxit-pdf-reader"`
3. Come back when done

2021-08-08 12:44 UTC, gitolicious commented
Thanks, that sounds like a reasonable approach. It's done.

2021-08-08 12:45 UTC, Ash258 requested changes
Move foxit-pdf-reader manifest into separate PR

2021-08-08 12:51 UTC, gitolicious commented
Sorry, I misunderstood. Done and added #6585

2021-11-04 09:48 UTC, issaclin32 approved these changes

2021-11-04 09:48 UTC, merged