Add VapourSynth Editor
ScoopInstaller/Extras pull request #6674
Opened 2021-08-21 16:53 UTC by SpecterShell

2021-10-30 19:01 UTC, pratikpc commented
@SpecterShell there is a GitHub repo with releases as well
https://github.com/vapoursynth/vapoursynth

2021-10-30 19:02 UTC, pratikpc commented
@SpecterShell the version the GitHub repo has is higher as well

2021-10-31 02:00 UTC, SpecterShell commented
> @SpecterShell there is a GitHub repo with releases as well [vapoursynth/vapoursynth](https://github.com/vapoursynth/vapoursynth)

This pr is VapourSynth**Editor**, not VapourSynth.

2021-11-01 04:45 UTC, rashil2000 commented
/verify

2021-11-01 04:49 UTC, rashil2000 requested changes

2021-11-01 04:49 UTC, rashil2000 commented on bucket/vapoursyntheditor.json
> +    "version": "r19",
The 'r' is not required, only 19 is sufficient. You will need to change the URLs and checkver too for this.

2021-11-01 05:19 UTC, rashil2000 approved these changes

2021-11-02 07:12 UTC, issaclin32 approved these changes

2021-11-02 07:13 UTC, merged