coretemp@1.7.1: Persist manually (to avoid app from crashing)
ScoopInstaller/Extras pull request #6868
Opened 2021-09-16 16:09 UTC by issaclin32

Since version 1.7, **CoreTemp** will crash on startup if encounters an empty config file (`CoreTemp.ini`).

This fixes the problem.

2021-09-18 17:45 UTC, Ash258 requested changes
Revert everything what you have done and change pre_install block to:

```json

    "pre_install": [
        "if (!(Test-Path \"$persist_dir\\CoreTemp.ini\")) {",
        "    Set-Content \"$dir\\CoreTemp.ini\" @('[General]', 'AutoUpdateCheck=0;') -Encoding 'Ascii'",
        "}"
    ],
```

![image](https://user-images.githubusercontent.com/13260377/133897774-0946db96-e731-46a1-8f47-074f5eb06a87.png)

2021-09-23 18:42 UTC, Ash258 commented
@issaclin32 Did you tested on clean environment after the newest changes?

2021-09-25 06:55 UTC, issaclin32 commented
> @issaclin32 Did you test on clean environment after the newest changes?

I found the problem on a new PC, and re-produced the problem on another new PC.
The CPUs are `Intel i7-9700F` and `AMD R9 5950X`.

However I cannot re-produce the problem on a VM (not sure about the reason)

2021-09-27 08:34 UTC, Ash258 commented
I really do not understand what you are trying to say.

Did it work with this fixed manifest or not?

2021-11-03 11:43 UTC, closed without merging