grepWin: Add checkver for automated updates
ScoopInstaller/Extras pull request #7201
Opened 2021-10-31 11:33 UTC by JamesCullum

Noticed that grepWin didn't get updated for quite a while, probably due to missing checkver.
Wanted to automate this using the Github repository with a small change - this should pick up the correct hashes at next update cycle.

2021-10-31 15:19 UTC, pratikpc approved these changes

2021-10-31 15:23 UTC, pratikpc requested changes
Hey we need to update the autoupdate URLs as well

https://github.com/stefankueng/grepWin/releases/download/2.0.8/grepWin-2.0.8_portable.exe#/grepWin.exe no longer exists

2021-10-31 15:59 UTC, JamesCullum commented
Thanks for the good comment!

The newest release has this URL: https://github.com/stefankueng/grepWin/releases/download/2.0.8/grepWin-x64-2.0.8_portable.zip
The file inside is called grepWin-x64-2.0.8_portable.exe

So I assume that the correct autoupdate URL would need to be https://github.com/stefankueng/grepWin/releases/download/$version/grepWin-x64-$version_portable.zip#/grepWin-x64-$version_portable.exe, right?

2021-10-31 16:01 UTC, pratikpc commented
No no

How can a ZIP file become an exe?

2021-10-31 16:06 UTC, JamesCullum commented
I see - the `#` then stands for renaming, I assumed it was for extraction.

I now simply used the MSI - let me know if this works for you 👍

2021-10-31 16:08 UTC, pratikpc commented
@JamesCullum please update the versions offline and check once if installation takes place properly.

Check if all persist based configurations work as well and share screenshots for all steps

Scoop usually prefers portable files so we are more likely to update to portable ZIP files.

2021-11-01 09:50 UTC, JamesCullum commented
Tested and updated - grepWin persist nowadays via registry.
The MSI is just a ZIP with the portable files, but packed with more translations.

2021-11-01 10:03 UTC, Valinor commented
> Tested and updated - grepWin persist nowadays via registry. The MSI is just a ZIP with the portable files, but packed with more translations.

No, I currently test it, and msi record grepwin.ini in AppData/Roaming/...
The portable version record the grepwin.ini in the current directory.

2021-11-01 10:38 UTC, JamesCullum commented
Good hint, didn't know that! Will take a look at the portable version then again!

2021-11-01 11:54 UTC, JamesCullum commented
Okay, I'm just renaming it via script now.

@Valinor I noticed that even the portable version in 2.0.8 doesn't automatically store the ini in the same folder. Its actually now only decided by the flag `/portable` flag, which I added to the shim. Maybe give it a try and let me know if it works 👍

2021-11-02 07:40 UTC, Valinor commented
@pratikpc Can you validate this push (approuve your "requested changes")? Seem that the next commit correct your point

2021-11-02 16:55 UTC, pratikpc commented
/verify

2021-11-02 16:56 UTC, pratikpc commented
@Valinor @JamesCullum could some screenshots be shared on this working with both 32 and 64 bit?

The manifest currently looks fine to me and passes verify too

2021-11-02 17:12 UTC, merged

2021-11-02 17:13 UTC, Valinor commented
![image](https://user-images.githubusercontent.com/2079654/139913024-d36f7c29-73f5-45cd-bba3-c30aef8c12cd.png)

![image](https://user-images.githubusercontent.com/2079654/139913097-f86bb2d0-bed2-47c8-9510-aa7d86897d86.png)

32bits and 64bits works for me.