Add Impregnate
ScoopInstaller/Extras pull request #7303
Opened 2021-11-11 12:31 UTC by Cr3atable

This pull request adds Impregnate (https://github.com/Cumcord/Impregnate), the installer for Cumcord (https://cumcord.com/).

Closes #7290

2021-11-11 12:35 UTC, pratikpc commented on bucket/impregnate.json
> +        "url": "https://github.com/Cumcord/Impregnate/releases/latest",
I would recommend following checkver: github format

2021-11-11 12:36 UTC, rashil2000 commented
Is the application 32bit or 64bit?

2021-11-11 12:36 UTC, Cr3atable commented
> Is the application 32bit or 64bit?

64 bit.

2021-11-11 12:38 UTC, pratikpc commented
Would recommend renaming to organisation name-package name.json

2021-11-11 12:40 UTC, rashil2000 commented
> > Is the application 32bit or 64bit?
> 
> 64 bit.

In that case, put the URL and hash in architecture block. And update the `autoupdate` section too

2021-11-11 12:48 UTC, Cr3atable commented
> > > Is the application 32bit or 64bit?
> > 
> > 
> > 64 bit.
> 
> In that case, put the URL and hash in architecture block. And update the `autoupdate` section too

Resolved

2021-11-11 12:50 UTC, pratikpc commented
@Cr3atable that won't work

2021-11-11 12:54 UTC, pratikpc requested changes
Correct license

Autoupdate is incorrect.

Regex probably is both incorrect and unnecessary

Will work with checkver: github as well

2021-11-11 12:54 UTC, pratikpc commented on bucket/impregnate.json
> +        "url": "https://github.com/Cumcord/Impregnate/releases/download/$version/impregnate.exe"
Is it 32 or 64 bit?

2021-11-11 12:54 UTC, pratikpc commented on bucket/impregnate.json
> +        "regex": "v(\\d\\.\\d+\\.\\d+),"
Is this needed?

2021-11-11 12:54 UTC, pratikpc commented on bucket/impregnate.json
> +    "license": "Apache-2.0",
License mentioned is MIT

https://github.com/Cumcord/Impregnate/blob/288f37d550218bdabc8dc4395c811a916d1170e9/LICENSE

2021-11-11 12:54 UTC, pratikpc commented on bucket/impregnate.json
> +        "url": "https://github.com/Cumcord/Impregnate/releases/download/$version/impregnate.exe"
Could you check if this application works with checkver.ps1 offline once with ForceUpdate parameter

https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate#using-checkverps1-to-query-and-autoupdate

2021-11-11 13:10 UTC, pratikpc commented
Can you upload a video or screenshots of what happens when you install the tool for the first time?

Is this an installer for another tool for example?

2021-11-11 13:13 UTC, lexisother commented
https://user-images.githubusercontent.com/54973868/141304245-dabed893-62b9-4f68-a73f-0f49a8a34952.mp4

2021-11-11 13:16 UTC, pratikpc commented
Thanks for sharing but this looks like an installer for another tool rather than the application itself.

I am not very aware of how Discord works but this app does not look very portable to me.

Views @rashil2000?

2021-11-11 13:18 UTC, pratikpc commented on bucket/impregnate.json
> +    "description": "A standalone installer for Cumcord.",
I would also recommend expanding on the definition and making it clear what the tool this installs does.

2021-11-11 13:24 UTC, pratikpc commented
@lexisother can we not install the tool this installs directly?

Instead of using another installer tool for the same purpose?

2021-11-11 13:25 UTC, lexisother commented
I'm unsure how that would work. The installation logic isn't exactly simple, and is best done by a tool such as this one.
See: https://github.com/Cumcord/Impregnate/blob/de15a565984f18f046fe75a6b1be8ba352778926/src/managerView.go#L33-L51

2021-11-11 13:41 UTC, pratikpc commented
@lexisother this looks like it could be doable with PowerShell

Maybe with an installer and uninstaller script. Scoop supports those.

But am still concerned about the portability of this solution. And what the update process would look like.

2021-11-11 13:49 UTC, Cr3atable commented
> @lexisother this looks like it could be doable with PowerShell
> 
> Maybe with an installer and uninstaller script. Scoop supports those.
> 
> But am still concerned about the portability of this solution. And what the update process would look like.

This software installs a modification for a non-portable app. The installer is portable, the app it installs to isn't. That's why scoop would not be a good fit for managing the installation or uninstallation of it.

2021-11-11 13:50 UTC, rashil2000 commented
I'm not much familiar with this application, but it looks like it installs mods in the Discord PC client?

@pratikpc we can't have manifests for each individual mod. But we can have one for a mod installer app.

2021-11-13 11:02 UTC, lexisother commented
Any news? @pratikpc

2021-11-13 11:35 UTC, pratikpc reviewed
Manifest looks fine.

I would like to know what happens when:-
1. Discord installed via Scoop receives an update
2. This ideally would change directory structure
3. Does this mean this setup ends up being completely broken and requires re-runs?
4. If true, add it to notes

I would recommend
1. Suggest block for Discord
2. Changing name of package to org name-app name or app name-setup because the app is far more recognized. (Evidence would be the difference in GitHub Stars).
Based on info received, this is an installer for an app
3. Also need to add notes detailing that the setup needs to be rerun after each and every update as it is not a very portable application.

I am still unsure if this should be added to Scoop due to a lack of portability. In my opinion, this is more suited for the NP bucket but if other maintainers choose to add, I personally have no issues

2021-11-13 12:20 UTC, lexisother commented
> Discord installed via Scoop receives an update
Nothing, for this program injects into the Discord `AppData` folder, not the directory where scoop installs Discord.

> This ideally would change directory structure
Directory structure of what?

> Does this mean this setup ends up being completely broken and requires re-runs?
No, refer to the first quote reply.

> I would suggest:
> Suggest block for Discord
On it.

> Changing name of package to org name-app name or app name-setup
Example? I don't follow.

> Also need to add notes detailing that the setup needs to be rerun after each and every update as it is not a very portable application.
False.

2021-12-29 10:10 UTC, rashil2000 requested changes
Update manifest to version 1.2.3

2021-12-29 10:10 UTC, rashil2000 commented on bucket/impregnate.json
> +    "bin": "impregnate.exe",
Does the binary take any commandline arguments? If not, remove this line.

2021-12-29 10:10 UTC, rashil2000 commented on bucket/impregnate.json
> +        ]
```suggestion
        "Discord": "extras/discord"
```

2021-12-29 10:21 UTC, rashil2000 requested changes

2021-12-29 10:21 UTC, rashil2000 commented on bucket/impregnate.json
> +    "shortcuts": [["impregnate.exe", "Impregnate"]],
Don't do this, this is hard to read. Revert to as it was before.

2021-12-29 10:26 UTC, rashil2000 commented
/verify

2021-12-29 10:32 UTC, merged