boostnote-app and boostnote-local:  Add version 0.23.1 (boostnote-app) and 0.22.3 (boostnote-local)
ScoopInstaller/Extras pull request #7535
Opened 2021-12-14 15:54 UTC by chenxiangfang

2021-12-14 16:01 UTC, rashil2000 commented
/verify

Do the binaries `Boost Note.exe` and `Boost Note - Local.exe` take any commandline arguments?

2021-12-14 16:05 UTC, rashil2000 requested changes

2021-12-14 16:05 UTC, rashil2000 commented on bucket/boostnote-local.json
> +        "url": "https://github.com/BoostIO/BoostNote.next-local/releases/download/vv$version/boost-note-local-win.exe#/dl.7z"
```suggestion
        "url": "https://github.com/BoostIO/BoostNote.next-local/releases/download/v$version/boost-note-local-win.exe#/dl.7z"
```

2021-12-21 09:59 UTC, issaclin32 commented
/verify

2021-12-21 10:28 UTC, issaclin32 submitted a review, later dismissed

2021-12-27 14:42 UTC, rashil2000 commented
There's already a manifest for boostnote.json. Please update that instead of creating new boostnote-app.json

2022-01-03 15:39 UTC, issaclin32 commented
/verify

2022-01-03 16:08 UTC, rashil2000 commented on bucket/boostnote.json
> +    "homepage": "https://github.com/BoostIO/BoostNote-App",
We can keep using boostnote.io as we already provide GitHub URL in checkver

2022-01-03 16:08 UTC, rashil2000 commented on bucket/boostnote-local.json
> +    "homepage": "https://github.com/BoostIO/BoostNote.next-local",
Same as above

2022-01-03 16:19 UTC, merged