gpxsee: Add version 10.0
ScoopInstaller/Extras pull request #7570
Opened 2021-12-21 12:49 UTC by 2ion

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

As for config persistence, this project is using Qt5 and QSettings to store and manage user preferences. QSettings uses the Windows registry on Windows platforms which I am not able to capture in the manifest. The only other sort of persistence is the tile cache in AppData/Local (also not captured).

2021-12-21 12:50 UTC, 2ion commented
/verify

2021-12-21 14:10 UTC, rashil2000 requested changes

2021-12-21 14:10 UTC, rashil2000 commented on bucket/gpxsee.json
> +    "license": "GPL3",
```suggestion
    "license": "GPL-3.0-only",
```

2021-12-21 14:10 UTC, rashil2000 commented on bucket/gpxsee.json
> +            "url": "https://jztkft.dl.sourceforge.net/project/gpxsee/Windows/GPXSee-10.0_x64.exe#/dl.7z",
```suggestion
            "url": "https://downloads.sourceforge.net/project/gpxsee/Windows/GPXSee-10.0_x64.exe#/dl.7z",
```

2021-12-21 14:10 UTC, rashil2000 commented on bucket/gpxsee.json
> +                "url": "https://jztkft.dl.sourceforge.net/project/gpxsee/Windows/GPXSee-$version_x64.exe#/dl.7z"
```suggestion
                "url": "https://downloads.sourceforge.net/project/gpxsee/Windows/GPXSee-$version_x64.exe#/dl.7z"
```

2021-12-21 14:10 UTC, rashil2000 commented
Any commandline arguments?

2021-12-21 14:27 UTC, 2ion commented
> Any commandline arguments?

Yes and no.

 * Default set of Qt common arguments supported, none relevant as far as I can tell though: https://doc.qt.io/qt-5/qguiapplication.html#supported-command-line-options. QSettings behaviour not modifyable as a constructor defaulting to the native settings format (on Windows: Registry https://doc.qt.io/qt-5/qsettings.html#platform-specific-notes) is used: https://github.com/tumic0/GPXSee/blob/master/src/GUI/gui.cpp#L2156
 * Simple positional arguments specifying files to load into the app by path supported in application code also not relevant: https://github.com/tumic0/GPXSee/blob/master/src/GUI/app.cpp#L78

2021-12-21 14:33 UTC, rashil2000 commented
Okay, then we don't need bin field

2021-12-22 10:40 UTC, rashil2000 commented
/verify

2021-12-22 10:42 UTC, merged