Cuetools: Update to version 2.1.9
ScoopInstaller/Extras pull request #7602
Opened 2021-12-26 11:56 UTC by Pachurii

Bump to Version 2.1.9, download location changed to github as per http://cue.tools/wiki/CUETools_Download#Download

- [ ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2021-12-26 11:56 UTC, Pachurii commented
/verify

2021-12-26 12:32 UTC, rashil2000 commented
Add checkver and autoupdate as well

2021-12-27 03:00 UTC, Pachurii commented
/verify

2021-12-27 03:28 UTC, Pachurii commented
/verify

2021-12-27 03:30 UTC, Pachurii commented
not sure why they do not pass, sorry @rashil2000

2021-12-27 06:49 UTC, rashil2000 requested changes

2021-12-27 06:49 UTC, rashil2000 commented on bucket/cuetools.json
> +    "checkver": "github",
This line works only when the homepage is a GitHub repository.

Use:
```json
"checkver": {
    "github": "https://github.com/gchudov/cuetools.net"
},
```

2021-12-27 07:07 UTC, rashil2000 commented
/verify

2021-12-27 07:22 UTC, merged