ultravnc: Add version 1.3.6.0
ScoopInstaller/Extras pull request #7612
Opened 2021-12-27 20:11 UTC by littleli

This adds UltraVNC.

*UltraVNC Server and Viewer are a powerful, easy to use, free software that can display the screen of
one computer (Server) on the screen of another (Viewer). The program allows the viewer to use their mouse
and keyboard to control the Server Computer remotely.
UltraVNC is a VNC application that is tailored towards Windows PCs, with several features not found
in other VNC products.*

Closes #7560 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2021-12-27 20:51 UTC, littleli commented
I don't understand why is PR checker unhappy ¯\_(ツ)_/¯

2021-12-28 06:12 UTC, rashil2000 requested changes

2021-12-28 06:12 UTC, rashil2000 commented on bucket/ultravnc.json
> +                "extract_dir": "x64"
```suggestion
                "url": "https://uvnc.com/component/jdownloads/send/0-/${1}-ultravnc-${2}-${3}-${4}${5}-bin-zip.html?Itemid=0#/dl.zip"
```

Updating extract_dir is not required

2021-12-28 06:12 UTC, rashil2000 commented on bucket/ultravnc.json
> +                "extract_dir": "x86"
```suggestion
                "url": "https://uvnc.com/component/jdownloads/send/0-/${1}-ultravnc-${2}-${3}-${4}${5}-bin-zip.html?Itemid=0#/dl.zip"
```

2021-12-28 08:49 UTC, rashil2000 commented
/verify

2021-12-28 08:52 UTC, rashil2000 commented
checkver is failing

2021-12-28 09:38 UTC, rashil2000 commented
/verify

2021-12-28 10:21 UTC, littleli commented
Currently:

```
      [-] ultravnc.json has 8 Errors!
      [*] Error: JSON does not match any schemas from 'anyOf'.
        [^] Line: C:\projects\scoopinstaller-extras\bucket\ultravnc.json:33:19
        [^] Path: http://scoop.sh/draft/schema#/definitions/autoupdate/AnyOf
        [*] Error: Property 'architecture' has not been defined and the schema does not allow additional properties.
          [^] Line: C:\projects\scoopinstaller-extras\bucket\ultravnc.json:34:23
          [^] Path: http://scoop.sh/draft/schema#/definitions/autoupdateArch/AdditionalProperties
        [*] Error: JSON does not match any schemas from 'anyOf'.
          [^] Line: C:\projects\scoopinstaller-extras\bucket\ultravnc.json:36:133
          [^] Path: http://scoop.sh/draft/schema#/definitions/autoupdateUriOrArrayOfAutoupdateUris/AnyOf
          [*] Error: Invalid type. Expected Array but got String.
            [^] Line: C:\projects\scoopinstaller-extras\bucket\ultravnc.json:36:133
            [^] Path: http://scoop.sh/draft/schema#/definitions/autoupdateUriOrArrayOfAutoupdateUris/anyOf/1/Type
          [*] Error: String 'https://uvnc.com/component/jdownloads/send/0-/${1}-ultravnc-${2}-${3}-${4}${5}-bin-zip.html?Itemid=0#/dl.zip' does not validate against format 'uri'.
            [^] Line: C:\projects\scoopinstaller-extras\bucket\ultravnc.json:36:133
            [^] Path: http://scoop.sh/draft/schema#/definitions/autoupdateUriOrArrayOfAutoupdateUris/anyOf/0/Format
        [*] Error: JSON does not match any schemas from 'anyOf'.
          [^] Line: C:\projects\scoopinstaller-extras\bucket\ultravnc.json:39:133
          [^] Path: http://scoop.sh/draft/schema#/definitions/autoupdateUriOrArrayOfAutoupdateUris/AnyOf
          [*] Error: Invalid type. Expected Array but got String.
            [^] Line: C:\projects\scoopinstaller-extras\bucket\ultravnc.json:39:133
            [^] Path: http://scoop.sh/draft/schema#/definitions/autoupdateUriOrArrayOfAutoupdateUris/anyOf/1/Type
          [*] Error: String 'https://uvnc.com/component/jdownloads/send/0-/${1}-ultravnc-${2}-${3}-${4}${5}-bin-zip.html?Itemid=0#/dl.zip' does not validate against format 'uri'.
            [^] Line: C:\projects\scoopinstaller-extras\bucket\ultravnc.json:39:133
            [^] Path: http://scoop.sh/draft/schema#/definitions/autoupdateUriOrArrayOfAutoupdateUris/anyOf/0/Format
      [-] ultravnc.json 40ms
        Expected 0, but got 8.
        79:                         $validator.Errors.Count | should -be 0
        at <ScriptBlock>, C:\projects\scoop\test\Scoop-Manifest.Tests.ps1: line 79
```

This is odd. My local checkver is not complaining.

![ultravnc1](https://user-images.githubusercontent.com/544082/147556298-4f1465ba-8f5d-4ecc-b373-080b0237eedb.png)

2021-12-28 17:48 UTC, rashil2000 commented
You can't use `{2}` in URL, you need to use variables names, like `$version` or `$matchTag` etc.

2021-12-28 23:27 UTC, littleli commented
> You can't use `{2}` in URL, you need to use variables names, like `$version` or `$matchTag` etc.

👍🏻 Updated based on https://scoop-docs.vercel.app/docs/concepts/App-Manifest-Autoupdate.html#captured-variables

2021-12-29 05:50 UTC, rashil2000 commented
/verify

Should we add a bin? I'm sure `vncviewer` supports commandline arguments, not sure about `winvnc` though.

2021-12-29 06:08 UTC, rashil2000 commented
The checkver logic you wrote captures filenum as 149. This is for the download page - https://uvnc.com/downloads/ultravnc/146-ultravnc-1-3-6-0.html, and not the download link itself. 

You might need to write a script in checkver to follow links, something like this - https://github.com/ScoopInstaller/Extras/pull/7586/files

2021-12-29 16:10 UTC, littleli commented
- I added `script` to checkver
- I added `bin` section, both binaries can take some command line parameters it seems

2021-12-29 16:49 UTC, rashil2000 commented
/verify

2021-12-29 17:01 UTC, rashil2000 requested changes

2021-12-29 17:01 UTC, rashil2000 commented on bucket/ultravnc.json
> +        }
```suggestion
        "url": "https://uvnc.com/component/jdownloads/send/0-/$matchDlquerypath#/dl.zip"
```

2021-12-29 17:07 UTC, rashil2000 commented
/verify

2021-12-29 17:29 UTC, merged