thsiswin11: Add version 1.0.50
ScoopInstaller/Extras pull request #7613
Opened 2021-12-27 22:48 UTC by littleli

*ThisIsWin11 lets you customize Windows 11 all in one place. It is slowly expanded as a practical all-rounder for Windows 11, similar to Microsoft PowerToys.*

Closes #7604

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2021-12-27 22:53 UTC, littleli commented
Maybe "notes" section which informs user that this package works only on Windows 11 is a good idea?

2021-12-28 05:56 UTC, rashil2000 requested changes

2021-12-28 05:56 UTC, rashil2000 commented on bucket/thisiswin11.json
> +    "description": "The real PowerToys for Windows 11",
```suggestion
    "description": "An all-rounder tool to set up and customize Windows 11",
```

2021-12-28 05:56 UTC, rashil2000 commented on bucket/thisiswin11.json
> +    "homepage": "https://www.builtbybel.com/blog/19-apps/43-try-the-new-thisiswin11-app-and-get-some-powertoys-for-windows-11",
```suggestion
    "homepage": "https://github.com/builtbybel/ThisIsWin11",
```

2021-12-28 05:56 UTC, rashil2000 commented on bucket/thisiswin11.json
> +            "Customize Windows 11"
```suggestion
            "ThisIsWin11"
```

2021-12-28 05:56 UTC, rashil2000 commented on bucket/thisiswin11.json
> +    },
```suggestion
    "checkver": "github",
```

2021-12-28 05:57 UTC, rashil2000 commented
> Maybe "notes" section which informs user that this package works only on Windows 11 is a good idea?

I think the name is enough for that.

Also, Win11 is 64bit only, so please use architecture blocks everywhere

2021-12-28 08:43 UTC, littleli commented
> > Maybe "notes" section which informs user that this package works only on Windows 11 is a good idea?
> 
> I think the name is enough for that.
> 
> Also, Win11 is 64bit only, so please use architecture blocks everywhere

Done. Thank you..

2021-12-28 08:45 UTC, rashil2000 commented
/verify

2021-12-28 09:37 UTC, merged