Add apkeep
ScoopInstaller/Extras pull request #7767
Opened 2022-01-17 20:08 UTC by kzshantonu

- [ x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2022-01-18 03:29 UTC, rashil2000 commented
Make this PR in Main bucket

2022-01-18 04:42 UTC, kzshantonu commented
> Make this PR in Main bucket

Does not fit the criteria for main bucket https://github.com/ScoopInstaller/Scoop/wiki/Criteria-for-including-apps-in-the-main-bucket

2022-01-18 04:58 UTC, rashil2000 requested changes

2022-01-18 04:58 UTC, rashil2000 commented on bucket/apkeep.json
> +    "description": "command-line tool for downloading APK files from various sources",
```suggestion
    "description": "Command-line tool for downloading APK files from various sources",
```

2022-01-18 04:58 UTC, rashil2000 commented on bucket/apkeep.json
> +    "hash": "2f0fedbf4243ca700be99f8a9890acf88e7b9c7f7891f25cd246ea00c3bd802a",
```suggestion
    "architecture": {
        "64bit": {
            "url": "https://github.com/EFForg/apkeep/releases/download/0.8.0/apkeep-x86_64-pc-windows-msvc.exe#/apkeep.exe",
            "hash": "2f0fedbf4243ca700be99f8a9890acf88e7b9c7f7891f25cd246ea00c3bd802a"
        }
    },
```

2022-01-18 04:58 UTC, rashil2000 commented on bucket/apkeep.json
> +        "url" : "https://github.com/EFForg/apkeep/releases/download/$version/apkeep-x86_64-pc-windows-msvc.exe#/apkeep.exe"
```suggestion
        "architecture": {
            "64bit": {
                "url" : "https://github.com/EFForg/apkeep/releases/download/$version/apkeep-x86_64-pc-windows-msvc.exe#/apkeep.exe"
            }
        }
```

2022-01-18 08:03 UTC, rashil2000 commented
Please make the requested changes

2022-01-18 08:09 UTC, rashil2000 commented
Inconsistent indentation. 

Pay close attention to the suggestions.

2022-01-18 08:21 UTC, rashil2000 commented
/verify

2022-01-18 08:26 UTC, merged

2022-02-21 08:28 UTC, snowman commented
> > Make this PR in Main bucket
> 
> Does not fit the criteria for main bucket https://github.com/ScoopInstaller/Scoop/wiki/Criteria-for-including-apps-in-the-main-bucket

Which point(s) do you think doesn't fit? 

I also want to send a pull request, but I don't know which repos should I send.

But I come across this pull request, I think `apkeep` is a [command-line tool](https://github.com/EFForg/apkeep/blob/master/USAGE), so the `apkeep.json` should go to the `Main` bucket.

> For an app to be acceptable for the main bucket, it should be:
> 
> 1. a reasonably well-known and widely used developer tool
> 2. the latest stable version of the program
> 3. the full version i.e. not a trial version
> 4. a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)
> 5. a non-GUI tool

2022-02-21 08:31 UTC, rashil2000 commented
> a reasonably well-known tool

It is less than a year old (not much popular)