qtemu: Add version 2.1
ScoopInstaller/Extras pull request #7770
Opened 2022-01-17 22:55 UTC by LazyGeniusMan

Closes #7769 

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2022-01-17 22:55 UTC, LazyGeniusMan commented
/verify

2022-01-18 04:31 UTC, rashil2000 requested changes
Anything to persist?

2022-01-18 04:31 UTC, rashil2000 commented on bucket/qtemu.json
> +    "extract_dir": "qtemu_portable_x86_64",
Move this to arch 64bit block

2022-01-18 11:45 UTC, LazyGeniusMan commented
> Anything to persist?

Nope, I seen nothing added after I configure the app and add a VM, probably it's on %APPDATA% for setting and %USER% for VM

2022-01-18 11:46 UTC, LazyGeniusMan commented
/verify

2022-01-18 11:53 UTC, merged