Updated youtube-dl-gui to v1.8.3
ScoopInstaller/Extras pull request #7814
Opened 2022-01-22 08:38 UTC by brian6932

Just updated the package, this version had a name change in the .msi and was not being auto updated, I am not entirely sure if I got the `checkver` and `autoupdate` syntax correct, so pls lmk

2022-01-22 21:40 UTC, HUMORCE requested changes

2022-01-22 21:40 UTC, HUMORCE commented on bucket/youtube-dl-gui.json
> +                    "url": "$baseurl/releases/download/v$version/SHA2-256SUMS"
```suggestion
                    "url": "$baseurl/SHA2-256SUMS"
```

2022-01-22 22:05 UTC, brian6932 commented on bucket/youtube-dl-gui.json
> +            "yt-dlg\\yt-dlg.exe",
@HUMORCE I tried this, but I was getting errors saying that the executable could not be found, but once I added `yt-dlg\\` it fixed the issue

2022-01-22 22:47 UTC, brian6932 commented
I get the same errors when my manifest looks like this:
```json
{
    "version": "1.8.3",
    "description": "A cross platform front-end GUI of the popular youtube-dl written in wxPython.",
    "homepage": "https://github.com/oleksis/youtube-dl-gui",
    "license": "Unlicense",
    "architecture": {
        "64bit": {
            "url": "https://github.com/oleksis/youtube-dl-gui/releases/download/v1.8.3/yt-dlg-20220118.2.msi#/dl.ism",
            "hash": "71d4fc4eea97199218fdde36717e90326ed0fd4bd980c6afbffc263514e34be9"
        }
    },
    "pre_install": [
        "$_args = @{",
        "    'Path' = \"$dir\\$fname\"",
        "    'DestinationPath' = \"$dir\"",
        "    'Removal' = $true",
        "}",
        "if (get_config 'MSIEXTRACT_USE_LESSMSI' $true) { $_args.Add('ExtractDir', 'APPDIR\\yt-dlg') } else { $_args.Add('ExtractDir', 'yt-dlg') }",
        "Expand-MsiArchive @_args"
    ],
    "shortcuts": [
        [
            "yt-dlg.exe",
            "yt-dlg"
        ]
    ],
    "checkver": {
        "github":"https://github.com/oleksis/youtube-dl-gui",
        "regex": "v(?<version>[\\d.]+)/(?<msi>.*).msi"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/oleksis/youtube-dl-gui/releases/download/v$version/$matchMsi.msi#/dl.ism",
                "hash":{
                    "url": "$baseurl/SHA2-256SUMS"
                }
            }
        }
    }
}
```
Console log:
```pwsh
❯ scoop install .\youtube-dl-gui.json
WARN  Purging previous failed installation of youtube-dl-gui.
Uninstalling 'youtube-dl-gui' ().
'youtube-dl-gui' was uninstalled.
Installing 'youtube-dl-gui' (1.8.3) [64bit]
Loading yt-dlg-20220118.2.msi from cache
Checking hash of yt-dlg-20220118.2.msi ... ok.
Running pre-install script...
Exception: C:\Users\username\scoop\apps\scoop\current\lib\core.ps1:516
Line |
 516 |          throw "Could not find '$(fname $from)'! (error $($proc.ExitCo …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find 'yt-dlg'! (error 16)
```
However, I get no errors, when it doesn't use `#/dl.ism` and `pre_install`, and just install the .msi:
```json
{
    "version": "1.8.3",
    "description": "A cross platform front-end GUI of the popular youtube-dl written in wxPython.",
    "homepage": "https://github.com/oleksis/youtube-dl-gui",
    "license": "Unlicense",
    "architecture": {
        "64bit": {
            "url": "https://github.com/oleksis/youtube-dl-gui/releases/download/v1.8.3/yt-dlg-20220118.2.msi",
            "hash": "71d4fc4eea97199218fdde36717e90326ed0fd4bd980c6afbffc263514e34be9"
        }
    },
    "shortcuts": [
        [
            "yt-dlg\\yt-dlg.exe",
            "yt-dlg"
        ]
    ],
    "checkver": {
        "github":"https://github.com/oleksis/youtube-dl-gui",
        "regex": "v(?<version>[\\d.]+)/(?<msi>.*).msi"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/oleksis/youtube-dl-gui/releases/download/v$version/$matchMsi.msi",
                "hash":{
                    "url": "$baseurl/SHA2-256SUMS"
                }
            }
        }
    }
}

```
Console logs:
```pwsh
❯ scoop install .\youtube-dl-gui.json
WARN  Purging previous failed installation of youtube-dl-gui.
Uninstalling 'youtube-dl-gui' ().
'youtube-dl-gui' was uninstalled.
Installing 'youtube-dl-gui' (1.8.3) [64bit]
Loading yt-dlg-20220118.2.msi from cache
Checking hash of yt-dlg-20220118.2.msi ... ok.
Extracting yt-dlg-20220118.2.msi ... done.
Linking ~\scoop\apps\youtube-dl-gui\current => ~\scoop\apps\youtube-dl-gui\1.8.3
Creating shortcut for yt-dlg (yt-dlg.exe)
'youtube-dl-gui' (1.8.3) was installed successfully!
```

2022-01-22 23:07 UTC, brian6932 commented
oh, I had to set `scoop config MSIEXTRACT_USE_LESSMSI false`, now it's fine, should that be included in `pre_isntall` somehow?

2022-01-22 23:19 UTC, brian6932 commented
So the 2 ways of getting this to work (for me) would be the following:
Direct .msi install:
```json
{
    "version": "1.8.3",
    "description": "A cross platform front-end GUI of the popular youtube-dl written in wxPython.",
    "homepage": "https://github.com/oleksis/youtube-dl-gui",
    "license": "Unlicense",
    "architecture": {
        "64bit": {
            "url": "https://github.com/oleksis/youtube-dl-gui/releases/download/v1.8.3/yt-dlg-20220118.2.msi",
            "hash": "71d4fc4eea97199218fdde36717e90326ed0fd4bd980c6afbffc263514e34be9"
        }
    },
    "shortcuts": [
        [
            "yt-dlg\\yt-dlg.exe",
            "yt-dlg"
        ]
    ],
    "checkver": {
        "github":"https://github.com/oleksis/youtube-dl-gui",
        "regex": "v(?<version>[\\d.]+)/(?<msi>.*).msi"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/oleksis/youtube-dl-gui/releases/download/v$version/$matchMsi.msi",
                "hash":{
                    "url": "$baseurl/SHA2-256SUMS"
                }
            }
        }
    }
}
```
with `#/dl.ism`:
```json
{
    "version": "1.8.3",
    "description": "A cross platform front-end GUI of the popular youtube-dl written in wxPython.",
    "homepage": "https://github.com/oleksis/youtube-dl-gui",
    "license": "Unlicense",
    "architecture": {
        "64bit": {
            "url": "https://github.com/oleksis/youtube-dl-gui/releases/download/v1.8.3/yt-dlg-20220118.2.msi#/dl.ism",
            "hash": "71d4fc4eea97199218fdde36717e90326ed0fd4bd980c6afbffc263514e34be9"
        }
    },
    "pre_install": [
        "scoop config MSIEXTRACT_USE_LESSMSI false",
        "$_args = @{",
        "    'Path' = \"$dir\\$fname\"",
        "    'DestinationPath' = \"$dir\"",
        "    'Removal' = $true",
        "}",
        "if (get_config 'MSIEXTRACT_USE_LESSMSI' $true) { $_args.Add('ExtractDir', 'APPDIR\\yt-dlg') } else { $_args.Add('ExtractDir', 'yt-dlg') }",
        "Expand-MsiArchive @_args"
    ],
    "shortcuts": [
        [
            "yt-dlg.exe",
            "yt-dlg"
        ]
    ],
    "checkver": {
        "github":"https://github.com/oleksis/youtube-dl-gui",
        "regex": "v(?<version>[\\d.]+)/(?<msi>.*).msi"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/oleksis/youtube-dl-gui/releases/download/v$version/$matchMsi.msi#/dl.ism",
                "hash":{
                    "url": "$baseurl/SHA2-256SUMS"
                }
            }
        }
    }
}

```
since people are having issues, is the latter preferable?

2022-01-22 23:36 UTC, brian6932 commented
Update: I swapped `scoop config MSIEXTRACT_USE_LESSMSI true` and it's still working without `"scoop config MSIEXTRACT_USE_LESSMSI false",`, I am not sure why my state was bugged, is there a reason why it could be between these 2 settings or something. It is a boolean, is it possible it was set to null somehow? I am very confused.

2022-01-23 04:53 UTC, HUMORCE commented
`pre_install` script in this manifest (consider)for the MSI package is packaged in a special method.

```
PS C:\Users\HUMOR> scoop config MSIEXTRACT_USE_LESSMSI
True
PS C:\Users\HUMOR> scoop install 1ocal/youtube-dl-gui
Installing 'youtube-dl-gui' (1.8.3) [64bit]
Loading yt-dlg-20220118.2.msi from cache
Checking hash of yt-dlg-20220118.2.msi ... ok.
Running pre-install script...
Linking ~\scoop\apps\youtube-dl-gui\current => ~\scoop\apps\youtube-dl-gui\1.8.3
Creating shortcut for yt-dlg (yt-dlg.exe)
'youtube-dl-gui' (1.8.3) was installed successfully!
PS C:\Users\HUMOR> scoop uninstall youtube-dl-gui
Uninstalling 'youtube-dl-gui' (1.8.3).
Removing shortcut ~\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\yt-dlg.lnk
Unlinking ~\scoop\apps\youtube-dl-gui\current
'youtube-dl-gui' was uninstalled.
PS C:\Users\HUMOR> scoop config MSIEXTRACT_USE_LESSMSI false
'MSIEXTRACT_USE_LESSMSI' has been set to 'false'
PS C:\Users\HUMOR> scoop install 1ocal/youtube-dl-gui
Installing 'youtube-dl-gui' (1.8.3) [64bit]
Loading yt-dlg-20220118.2.msi from cache
Checking hash of yt-dlg-20220118.2.msi ... ok.
Running pre-install script...
Linking ~\scoop\apps\youtube-dl-gui\current => ~\scoop\apps\youtube-dl-gui\1.8.3
Creating shortcut for yt-dlg (yt-dlg.exe)
'youtube-dl-gui' (1.8.3) was installed successfully!
```

2022-01-23 04:54 UTC, HUMORCE requested changes
formatting

2022-01-23 04:54 UTC, HUMORCE commented on bucket/youtube-dl-gui.json
> +        "github":"https://github.com/oleksis/youtube-dl-gui",
```suggestion
        "github": "https://github.com/oleksis/youtube-dl-gui",
```

2022-01-23 04:54 UTC, HUMORCE commented on bucket/youtube-dl-gui.json
> +                "hash":{
```suggestion
                "hash": {
```

2022-01-23 05:02 UTC, brian6932 commented
> `pre_install` script in this manifest (consider)for the MSI package is packaged in a special method.

@HUMORCE I know, but if I had not previously defined the value `MSIEXTRACT_USE_LESSMSI`, what does it default to? I was getting errors previously, but after I set it to false, I stopped getting errors, even when I set it to true, I wasn't getting issues anymore. I am no longer able to reproduce my previous issues. The if else statement should cover if it's set to null, no? Is there some predefined value or null coalescing? I'm just trying to figure out what happened.

2022-01-23 05:14 UTC, HUMORCE commented
you are right, i have always keep this option in the config, so i have not touch this error before.

```
PS C:\Users\HUMOR> scoop config rm MSIEXTRACT_USE_LESSMSI
'MSIEXTRACT_USE_LESSMSI' has been removed
PS C:\Users\HUMOR> scoop install 1ocal/youtube-dl-gui
Installing 'youtube-dl-gui' (1.8.3) [64bit]
Loading yt-dlg-20220118.2.msi from cache
Checking hash of yt-dlg-20220118.2.msi ... ok.
Running pre-install script...
DEBUG[1642914560] $out = -------------------------------------------------------------------------------
   ROBOCOPY     ::     Robust File Copy for Windows
-------------------------------------------------------------------------------

  Started : Sunday, January 23, 2022 5:09:20 AM
   Source : C:\Users\HUMOR\scoop\apps\youtube-dl-gui\1.8.3\_tmp\SourceDir\APPDIR\yt-dlg\
     Dest : C:\Users\HUMOR\scoop\apps\youtube-dl-gui\1.8.3\

    Files : *.*

  Options : *.* /S /E /DCOPY:DA /COPY:DAT /MOVE /R:1000000 /W:30

------------------------------------------------------------------------------

2022/01/23 05:09:20 ERROR 3 (0x00000003) Accessing Source Directory C:\Users\HUMOR\scoop\apps\youtube-dl-gui\1.8.3\_tmp\SourceDir\APPDIR\yt-dlg\
The system cannot find the path specified. -> C:\Users\HUMOR\scoop\apps\scoop\current\lib\core.ps1:515:9
Exception: C:\Users\HUMOR\scoop\apps\scoop\current\lib\core.ps1:516
Line |
 516 |          throw "Could not find '$(fname $from)'! (error $($proc.ExitCo …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find 'yt-dlg'! (error 16)
```

2022-01-23 05:21 UTC, HUMORCE commented
test, then replace `pre_install` section with:

```
    "pre_install": [
        "$_args = @{",
        "    'Path' = \"$dir\\$fname\"",
        "    'DestinationPath' = \"$dir\"",
        "    'Removal' = $true",
        "}",
        "$LESSMSI = get_config 'MSIEXTRACT_USE_LESSMSI'",
        "if ($LESSMSI) { $_args.Add('ExtractDir', 'APPDIR\\yt-dlg') } else { $_args.Add('ExtractDir', 'yt-dlg') }",
        "Expand-MsiArchive @_args"
    ],
```

2022-01-23 05:31 UTC, brian6932 commented
@HUMORCE can confirm this fixed it, nice, you want to commit it, or should I?

2022-01-23 06:11 UTC, HUMORCE commented
yes, pls

2022-01-23 06:39 UTC, HUMORCE approved these changes

2022-01-23 06:53 UTC, rashil2000 commented
/verify

2022-01-23 06:55 UTC, merged

2022-02-20 13:08 UTC, candrapersada commented
why yt-dlg error for windows 7?
![image](https://user-images.githubusercontent.com/36833664/154844077-eb41a9b5-a624-47a3-82e4-3d43f343a064.png)
![image](https://user-images.githubusercontent.com/36833664/154844095-511ef0df-4051-4503-853f-67fdab6366f6.png)
and why use `.msi` not `.exe`

2022-02-20 14:12 UTC, brian6932 commented
@candrapersada 
> why use `.msi` not `.exe`

Just preference, the `.msi` is more complete to me

> why yt-dlg error for windows 7?

You can't honestly expect people to support a 9 yr old OS

2022-02-22 08:00 UTC, candrapersada commented
why is there no portable version like this?
```
		"if (!(Test-Path \"$dir\\User Data\\*\") -and (Test-Path \"$env:AppData\\yt-dlg\\User Data\")) {",
		"    info '[Portable Mode]: Copying user data...'",
		"    Copy-Item \"$env:AppData\\yt-dlg\\User Data\\*\" \"$dir\\User Data\" -Recurse",
		"}"
    ],
    "shortcuts": [
        [
            "yt-dlg.exe",
            "yt-dlg",
			"--user-data-dir=\"$dir\\User Data\""
```

2022-02-22 22:06 UTC, brian6932 commented
@candrapersada No one is stopping you from making one, just make a portable version, this has always used msi, even in the previous fork, so I just adjusted for the new one