Update to version 2.3.0
ScoopInstaller/Extras pull request #7834
Opened 2022-01-26 11:32 UTC by Gladtbam

2022-01-26 13:25 UTC, rashil2000 commented
Add autoupdate too. See https://github.com/ScoopInstaller/Extras/commit/9d2f42d1679a8a61d6b827d3e78ef553016e923c#diff-5d13722ca8a08c50336c43f12427760d5bedc4599358b8e0c92cd3594062ddfd for reference.

2022-01-26 14:53 UTC, rashil2000 commented
/verify

2022-01-26 15:17 UTC, rashil2000 requested changes
They now provide 32bit release. Add that too. https://github.com/Molunerfinn/PicGo/releases/download/v2.3.0/PicGo-Setup-2.3.0-ia32.exe

2022-01-26 15:17 UTC, rashil2000 commented on bucket/picgo.json
> +                "url": "https://github.com/Molunerfinn/PicGo/releases/download/v$version/PicGo-Setup-$version.exe#/dl.7z",
```suggestion
                "url": "https://github.com/Molunerfinn/PicGo/releases/download/v$version/PicGo-Setup-$version-x64.exe#/dl.7z",
```

2022-01-27 01:58 UTC, Gladtbam commented
Their latest.yml file does not provide a hash of x32bit.

2022-01-27 10:16 UTC, rashil2000 commented
> Their latest.yml file does not provide a hash of x32bit.

The latest.yml file for their next beta release `2.3.1-beta.2` contains hash for 32bit. Looks like they forgot to do that for `2.3.0`. Can you open an issue there to remind them to include it?

2022-01-27 10:52 UTC, rashil2000 requested changes

2022-01-27 10:52 UTC, rashil2000 commented on bucket/picgo.json
> +                "Expand-7zipArchive \"$dir\\`$PLUGINSDIR\\app-ia32.7z\" \"$dir\"",
```suggestion
                "Expand-7zipArchive \"$dir\\`$PLUGINSDIR\\app-32.7z\" \"$dir\"",
```

You should always confirm/check installation for 32bit by running `scoop install <filename>.json -a 32bit`

2022-01-27 14:38 UTC, Gladtbam commented
Now, they added hash for 32bit. But I  do not understand how to write `regex` for 32bit.
As you can see, I just copy-pasted for now

2022-01-27 17:37 UTC, rashil2000 commented
Check if this works `(?sm)ia32\\.exe?.*$base64`

2022-01-28 11:03 UTC, Gladtbam commented
There is one thing I don't quite understand. Why the obtained hash is `hash 256` instead of `hash 512`
![image](https://user-images.githubusercontent.com/49943258/151535995-5e01eb0f-2bae-4625-931b-f2b3b4209019.png)

2022-01-28 12:56 UTC, rashil2000 commented
Because they provide sha512 in the yml file. If it was sha256, we'd get hash 256

2022-01-28 13:12 UTC, Gladtbam commented
> Because they provide sha512 in the yml file. If it was sha256, we'd get hash 256
> 
> Also, you can comment `/verify` to see if your changes pass 

OK, I may have misinterpreted what I said.

They provided hash 512, but got hash 256 by checkver.ps1 instead. Why?

2022-01-28 13:22 UTC, Gladtbam commented
/verify

2022-01-28 14:00 UTC, Gladtbam commented
/verify

2022-01-28 14:04 UTC, Gladtbam commented
OK! I deleted `"url": "$baseurl/latest.yml"`. Now it works fine.

2022-01-28 16:19 UTC, niheaven commented
You now has wrong au.hash...

2022-01-28 16:30 UTC, niheaven commented
```json
"hash": {
    "url": "$baseurl/latest.yml",
    "regex": "(?s)$basename.*?$sha512"
}
```

This should work, put it outsides au arch, it's noarch hash extraction script.

2022-01-29 03:12 UTC, Gladtbam commented
> You now has wrong au.hash...

No. In fact, it gets the correct `hash 256`.

实际上得到的hash 256是正确的，它通过将文件下载下来得到的

2022-01-29 03:21 UTC, Gladtbam commented
> ```json
> "hash": {
>     "url": "$baseurl/latest.yml",
>     "regex": "(?s)$basename.*?$sha512"
> }
> ```
> 
> This should work, put it outsides au arch, it's noarch hash extraction script.

use it, PowerShell reply `Could not find hash in *.../latest.yml`
And reply `Downloading ...exe to compute hashes`

用这个scoop报在latest.yml文件中找不到hash，然后会下载文件计算hash 256

2022-01-29 04:26 UTC, Gladtbam commented
/verify

2022-01-29 07:23 UTC, issaclin32 commented
The checksum is encoded in Base64 (`sha512: yB7AmmEt6Qw5gtxQjtgWIHAsV3oyiPoVrfcd6gre5/428w+S7UoaWmTVyXH6xo9gO9HNTlUcOt90I2DE2ha8Dg==`)
It will work if we use **$base64**.

```
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/Molunerfinn/PicGo/releases/download/v$version/PicGo-Setup-$version-x64.exe#/dl.7z"
            },
            "32bit": {
                "url": "https://github.com/Molunerfinn/PicGo/releases/download/v$version/PicGo-Setup-$version-ia32.exe#/dl.7z"
            }
        },
        "hash": {
            "url": "$baseurl/latest.yml",
            "regex": "(?s)$basename.*?$base64"
        }
    }
```

2022-01-29 07:42 UTC, niheaven commented
Yes, it should be `$base64`. I typed the code by phone and made a mistake.

2022-01-29 07:47 UTC, Gladtbam commented
> The checksum is encoded in Base64 (`sha512: yB7AmmEt6Qw5gtxQjtgWIHAsV3oyiPoVrfcd6gre5/428w+S7UoaWmTVyXH6xo9gO9HNTlUcOt90I2DE2ha8Dg==`) It will work if we use **$base64**.
> 
> ```
>     "autoupdate": {
>         "architecture": {
>             "64bit": {
>                 "url": "https://github.com/Molunerfinn/PicGo/releases/download/v$version/PicGo-Setup-$version-x64.exe#/dl.7z"
>             },
>             "32bit": {
>                 "url": "https://github.com/Molunerfinn/PicGo/releases/download/v$version/PicGo-Setup-$version-ia32.exe#/dl.7z"
>             }
>         },
>         "hash": {
>             "url": "$baseurl/latest.yml",
>             "regex": "(?s)$basename.*?$base64"
>         }
>     }
> ```

Yes, this's OK!

2022-01-29 07:55 UTC, niheaven commented
You should use one au.hash, just likes @issaclin32 comment.

2022-01-29 08:03 UTC, niheaven commented
/verify

2022-01-29 08:03 UTC, Gladtbam commented
I might know why I get it wrong when I use `(?s)$basename.*?$base64`
Thanks

2022-01-29 08:06 UTC, niheaven commented
You put `(?s)` in wrong place, right? 😁

2022-01-29 08:07 UTC, niheaven approved these changes

2022-01-29 08:16 UTC, Gladtbam commented
You may not believe it, it parses the correct md5😭

2022-01-29 08:19 UTC, merged