ani-cli: Add version 1.6
ScoopInstaller/Extras pull request #7882
Opened 2022-01-31 20:54 UTC by RaynardGerraldo

ani-cli : A cli to browse and watch anime. This tool scrapes the site gogoanime.

- [ ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2022-01-31 20:55 UTC, RaynardGerraldo commented
/verify

2022-02-01 05:02 UTC, rashil2000 requested changes

2022-02-01 05:02 UTC, rashil2000 commented on bucket/ani-cli.json
> +    "license": "GPL-3.0",
```suggestion
    "license": "GPL-3.0-or-later",
```

2022-02-01 05:02 UTC, rashil2000 commented on bucket/ani-cli.json
> +    "description": "A cli to browse and watch anime. This tool scrapes the site gogoanime.",
```suggestion
    "description": "A CLI to browse and watch anime. This tool scrapes the site gogoanime.",
```

2022-02-01 05:06 UTC, RaynardGerraldo commented
Thanks @rashil2000

2022-02-01 05:10 UTC, merged