add-kapow
ScoopInstaller/Extras pull request #7892
Opened 2022-02-02 08:54 UTC by zStruCat

Kapow is a portable program to help tracking spent time
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2022-02-02 08:55 UTC, zStruCat commented
/verify

2022-02-02 08:56 UTC, zStruCat commented
/verify

2022-02-02 14:15 UTC, rashil2000 requested changes

2022-02-02 14:15 UTC, rashil2000 commented on bucket/kapow-punch-clock.json
> +    "extract_to": "",
```suggestion
```

2022-02-02 14:15 UTC, rashil2000 commented on bucket/kapow-punch-clock.json
> +    },
```suggestion
    "checkver": ">Version ([\\d\\.]+)<",
```

2022-02-02 14:15 UTC, rashil2000 commented
This is 64bit app. Use architecture block.

2022-02-02 15:30 UTC, zStruCat commented
/verify
manifest changed to architecture.64bits

2022-02-02 18:01 UTC, rashil2000 commented on bucket/kapow-punch-clock.json
> +    "description": "A portable program to help tracking spent time",
```suggestion
    "description": "A punch clock program to help in tracking spent time",
```

2022-02-03 05:33 UTC, zStruCat commented
> Rename app to just kapow.json

I used the name deliberately as there're other [program](https://github.com/BBVA/kapow) named as kapow. And i don't want to take risk.

2022-02-03 06:08 UTC, rashil2000 commented
> > Rename app to just kapow.json
> 
> I used the name deliberately as there're other [program](https://github.com/BBVA/kapow) named as kapow. And i don't want to take risk.

Ah, didn't know about it. Thanks for letting me know.

2022-02-03 06:09 UTC, merged