deadbeef: Update to 1.8.8
ScoopInstaller/Extras pull request #8033
Opened 2022-02-23 12:41 UTC by mxarcher

Closes #8027

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2022-02-23 12:50 UTC, mxarcher commented
/verify

2022-02-23 18:53 UTC, rashil2000 requested changes

2022-02-23 18:53 UTC, rashil2000 commented on bucket/deadbeef.json
> +    "description": "DeaDBeeF (as in 0xDEADBEEF) is a modular cross-platform audio player which runs on GNU/Linux distributions, macOS, Windows, *BSD, OpenSolaris, and other UNIX-like systems.",
```suggestion
    "description": "DeaDBeeF (as in 0xDEADBEEF) is a modular cross-platform audio player.",
```

2022-02-23 18:53 UTC, rashil2000 commented on bucket/deadbeef.json
> +    ],
```suggestion
    "persist": "config",
```

2022-02-24 04:26 UTC, mxarcher commented on bucket/deadbeef.json
>      "bin": "deadbeef.exe",
Sorry, I forget to check what innosetup mean.

2022-02-24 04:40 UTC, rashil2000 commented on bucket/deadbeef.json
>      "bin": "deadbeef.exe",
In that case the `bin` entry can be removed

2022-02-24 04:44 UTC, mxarcher commented on bucket/deadbeef.json
>      "bin": "deadbeef.exe",
OK, I'll remove it.

2022-02-24 04:53 UTC, rashil2000 commented
/verify

2022-02-24 04:58 UTC, merged