libgen-desktop: Add version 1.4.1
ScoopInstaller/Extras pull request #8041
Opened 2022-02-24 17:13 UTC by zStruCat

As its name implies, libgen-desktop is a client for library genesis.
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2022-02-24 17:13 UTC, zStruCat commented
/verify

2022-02-24 19:43 UTC, rashil2000 requested changes

2022-02-24 19:43 UTC, rashil2000 commented on bucket/libgen-desktop.json
> +    "description": "Desktop for Library Gensis",
```suggestion
    "description": "Desktop application for Library Genesis",
```

2022-02-24 19:43 UTC, rashil2000 commented on bucket/libgen-desktop.json
> +    ],
```suggestion
```

This section is not required. Scoop is only supported on Windows 7 and above (which already have this).

2022-02-24 19:43 UTC, rashil2000 commented on bucket/libgen-desktop.json
> +    "extract_to": "",
```suggestion
```

2022-02-24 19:43 UTC, rashil2000 commented on bucket/libgen-desktop.json
> +    "checkver": "github",
```suggestion
```

I don't think this app is going to get any updates (the github repo is abandoned). So we can remove this field.

2022-02-24 19:43 UTC, rashil2000 commented on bucket/libgen-desktop.json
> +    ],
The proper way to do this is like this:
https://github.com/ScoopInstaller/Extras/blob/59b802f3e6b9b9b52c3c632d449afb48f54f023c/bucket/xmplay.json#L8-L12

2022-02-25 01:38 UTC, zStruCat commented
/verify
Change has been made according to review opinion

2022-02-25 04:47 UTC, rashil2000 requested changes

2022-02-25 04:47 UTC, rashil2000 commented on bucket/libgen-desktop.json
> +    ],
```suggestion
    "notes": "For information of latest available libgen mirrors, see https://wiki.mhut.org/_media/software:libgen_desktop_mirrors_update.zip",
```

2022-02-25 05:29 UTC, merged