Add: Quassel
ScoopInstaller/Extras pull request #8171
Opened 2022-03-17 22:38 UTC by SonaliBendre

Closes #XXXX

Relates to #XXXX

- [ ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2022-03-18 04:13 UTC, rashil2000 commented
- Order of fields not followed
- Outdated SPDX License identifier
- Is this a 32bit or 64bit app?
- Do all the binaries support commandline arguments?

2022-03-18 08:57 UTC, issaclin32 commented on bucket/quassel.json
> +    "license": "GPL-2.0|GPL-3.0",
```suggestion
    "license": "GPL-2.0-or-later|GPL-3.0-or-later",
```
Check **"Identifier"** at https://spdx.org/licenses/

https://github.com/quassel/quassel/blob/master/gpl-3.0.txt has `or any later versions` in it, therefore it is `GPL-3.0-or-later`.

2022-03-18 11:08 UTC, issaclin32 commented on bucket/quassel.json
> +    "url": "https://quassel-irc.org/pub/quassel-windows-0.14.0.7z",
You can check the app is 32 or 64-bit using pelook (`scoop install pelook`)
If the app is 32-bit, then keep as it is (both 32-bit and 64-bit machine can run it)
If the app is 64-bit. then use
```
"architecture" {
    "64bit":  {
        "url": ...
        "hash": ...
    }
```

2022-03-18 11:11 UTC, issaclin32 commented
`bin` is only needed if  (1) The app is supposed to run under command-line, or (2) The app supports command-line arguments.

You can either check [readme](https://github.com/quassel/quassel/blob/master/README.md) or read the source code on main program to find it out. In the case of *quassel*, there are some command-line arguments.
```
Once you've set up Quassel, you may:

Add more users: quasselcore --add-user
Change the password of an existing user: quasselcore --change-userpass=username
See all available options: quasselcore --help
```

2022-03-26 07:46 UTC, issaclin32 commented
I updated the manifest because the author has not responded for a while.

**NOTES**:
* The app is built in 64-bit.
* **quassel** supports command-line args. See [ReadMe](https://github.com/quassel/quassel/blob/master/README.md) for example.
* *persist* is not needed because config is at `$Env:AppData\quassel-irc.org`. I tried tweaking some settings and creating profiles/connections, but `$dir\config` does not appear.

2022-03-26 07:46 UTC, issaclin32 commented
/verify

2022-03-26 08:14 UTC, rashil2000 requested changes
We should wrap the `$dir\\config` part in double quotes to account for spaces in path

2022-03-26 08:44 UTC, rashil2000 approved these changes

2022-03-26 11:26 UTC, merged