min: Add version 1.24.0
ScoopInstaller/Extras pull request #8355
Opened 2022-04-20 19:12 UTC by nohopestage

Closes #8354

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2022-04-20 19:12 UTC, nohopestage commented
/verify

2022-04-20 19:56 UTC, rashil2000 commented
If an app does not natively store data in its own directory, we shouldn't try to force persistence. (The chrome manifests are an exception to this because of backward compatibility). 

Storing data in AppData is fine.

2022-04-20 20:14 UTC, nohopestage commented
This is exactly how it's done in [ungoogled-chromium](https://github.com/lukesampson/scoop-extras/tree/master/bucket/ungoogled-chromium.json), and Min is basically chromium.

2022-04-20 20:28 UTC, rashil2000 commented
> (The older chrome manifests are an exception to this because of backward compatibility)

2022-04-20 20:55 UTC, nohopestage commented
/verify

2022-04-20 21:30 UTC, nohopestage commented
Removed persistence, the app now stores its data in AppData.

2022-04-21 14:16 UTC, rashil2000 requested changes

2022-04-21 14:16 UTC, rashil2000 commented on bucket/min.json
> +            "hash": "e00a9d6e7652fd4dd40dda83fb8b316016f21503f25f2a1cb9be88d21c9e5c65"
```suggestion
            "hash": "e00a9d6e7652fd4dd40dda83fb8b316016f21503f25f2a1cb9be88d21c9e5c65",
            "extract_dir": "Min-v1.24.0"
```

2022-04-21 14:16 UTC, rashil2000 commented on bucket/min.json
> +    ],
```suggestion
    "bin": "Min.exe",
```

2022-04-21 14:16 UTC, rashil2000 commented on bucket/min.json
> +        "url": "https://github.com/minbrowser/min/releases/latest/download/Min-v$version-win32-x64.zip"
```suggestion
        "architecture": {
            "64bit": {
                "url": "https://github.com/minbrowser/min/releases/latest/download/Min-v$version-win32-x64.zip"
                "extract_dir": "Min-v$version"
            }
        }
```

2022-04-21 15:20 UTC, merged