polsedit: Add version latest
ScoopInstaller/Extras pull request #8505
Opened 2022-05-19 11:20 UTC by TamamoNoMae13

- [ x ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2022-05-19 21:19 UTC, rashil2000 requested changes

2022-05-19 21:19 UTC, rashil2000 commented on bucket/polsedit.json
> +    "version": "latest",
```suggestion
    "version": "1.0.0.5",
```

2022-05-19 21:19 UTC, rashil2000 commented on bucket/polsedit.json
> +            "bin": "polseditx64.exe",
```suggestion
            "bin": [
                [
                    "polseditx64.exe",
                    "polsedit"
                ]
            ],
```

2022-05-19 21:19 UTC, rashil2000 commented on bucket/polsedit.json
> +            "bin": "polseditx32.exe",
```suggestion
            "bin": [
                [
                    "polseditx32.exe",
                    "polsedit"
                ]
            ],
```

2022-05-20 06:27 UTC, rashil2000 commented
This is a GUI application, right? Does it support CLI arguments?

2022-05-20 08:10 UTC, TamamoNoMae13 commented
> This is a GUI application, right? Does it support CLI arguments?

As far as I tried, no.

2022-05-20 08:22 UTC, rashil2000 commented
In that case the bin fields can be removed

2022-05-20 09:32 UTC, rashil2000 commented
/verify

2022-05-20 09:39 UTC, merged