ani-cli: Update to version 3.3
ScoopInstaller/Extras pull request #8891
Opened 2022-07-18 09:31 UTC by port19x

Time to bump ani-cli. I'll release sometime today

- [ ] I have prepared the release upstream

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2022-07-20 03:20 UTC, sitiom requested changes

2022-07-20 03:20 UTC, sitiom commented on bucket/ani-cli.json
>      "license": "GPL-3.0-or-later",
```suggestion
    "license": "GPL-3.0-or-later",
    "suggest": {
        "git": "git"
    },
```

Suggest Git Bash requirement, in line with the other shell scripts in this bucket.

2022-07-25 13:26 UTC, port19x commented
There will be a seperate PR to update to v3.3

2022-07-25 13:26 UTC, closed without merging

2022-08-05 21:15 UTC, port19x commented
If I remember, sure