add WSL-distrod 0.1.7
ScoopInstaller/Extras pull request #9116
Opened 2022-08-27 17:05 UTC by Slach

## WSL-distrod

Distrod is a meta-distro for WSL 2 which installs Ubuntu, Arch, Debian, Gentoo, etc. with systemd in a minute for you. Distrod also has built-in auto-start feature on Windows startup and port forwarding ability.

2022-08-27 17:06 UTC, Slach commented
don't understand why 500 commits in pull request i just make 
```
git pull origin master
git checkout -b wsl-distrod
create file bucket/wsl-distrod.json
and 
git push origin wsl-distrod
```

2022-08-31 11:40 UTC, igitur commented
Please rebase on `master` branch.

2022-09-20 19:39 UTC, Slach commented
@igitur commits rebased and squashed
could you please review again?

2022-09-21 03:16 UTC, niheaven requested changes

2022-09-21 03:16 UTC, niheaven commented on bucket/wsl-distrod.json
> +    "description": "Distrod is a meta-distro for WSL 2 which installs Ubuntu, Arch, Debian, Gentoo, etc. with systemd in a minute for you. Distrod also has built-in auto-start feature on Windows star
```suggestion
    "description": "A meta-distro for WSL 2 which installs Ubuntu, Arch, Debian, Gentoo, etc. with systemd in a minute for you",
```

2022-09-21 03:16 UTC, niheaven commented on bucket/wsl-distrod.json
> +            "bin": "distrod_wsl_launcher-x86_64\\distrod_wsl_launcher.exe"
```suggestion
            "extract_dir": "distrod_wsl_launcher-x86_64"
```

2022-09-21 03:16 UTC, niheaven commented on bucket/wsl-distrod.json
> +    },
```suggestion
    },
    "bin": "distrod_wsl_launcher.exe",
```

2022-09-21 03:42 UTC, Slach commented
@niheaven thanks for review, suggestions committed

2022-09-21 05:22 UTC, niheaven approved these changes

2022-09-21 05:22 UTC, merged