Arduino IDE: add version 2.0.0
ScoopInstaller/Extras pull request #9266
Opened 2022-09-20 05:09 UTC by sayeed205

Updated version for Arduino IDE

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2022-09-20 09:55 UTC, tech189 requested changes
Thanks for your PR! I've made a few fixes - in future do test out your manifest with `scoop install <path to your manifest>` to check it installs.

2022-09-20 09:55 UTC, tech189 commented on bucket/arduino.json
> +    "extract_dir": "arduino-2.0.0",
Remove extract_dir as this directory no longer exists in version 2.0.0. Please also remove it from autoupdate.

2022-09-20 09:55 UTC, tech189 commented on bucket/arduino.json
>          },
```suggestion
```
Remove hash from autoupdate as hashes are no longer provided on the website. (Hashes on GitHub releases are only for the .exe download, sadly)

2022-09-20 10:00 UTC, tech189 commented
I think we have to also remove the `pre_install` script, the `post_install` script, and the `persist` section as none of the files referred to exist in this version. I think the IDE now stores the plugins, preferences, and hardware config in `\AppData\Local\Arduino15`

2022-09-23 01:00 UTC, tech189 commented
> I think we have to also remove the `pre_install` script...

Thanks for applying my review suggestions! Could you please follow my suggestions I partially quoted above?

The extract_dir needs to be removed too as it currently fails to install.

2022-09-23 01:26 UTC, sayeed205 commented
> The extract_dir needs to be removed too as it currently fails to install.

You mean the [auto update extract_dir](https://github.com/sayeed205/Extras/blob/b3807eee5171395285cd1eb744a0a69a565ae02d/bucket/arduino.json#L38) or [installation extract_dir](https://github.com/sayeed205/Extras/blob/b3807eee5171395285cd1eb744a0a69a565ae02d/bucket/arduino.json#L8)

2022-09-23 08:29 UTC, tech189 commented
Both as the enclosing folder "arduino-..." is no longer in the zip package, all files are in the root folder.

2022-09-23 08:33 UTC, sayeed205 commented
> Both as the enclosing folder "arduino-..." is no longer in the zip package, all files are in the root folder.

Sir you do necessary changes. Actually I(noob) dunno much about how scoop does things.

2022-09-23 09:22 UTC, tech189 approved these changes

2022-09-23 09:22 UTC, tech189 commented
/verify

2022-09-24 09:25 UTC, issaclin32 approved these changes

2022-09-24 09:25 UTC, merged