mp3tag: Enhance `pre_install` script, add `pre_uninstall`, and change `persist`
ScoopInstaller/Extras pull request #9840
Opened 2022-11-25 06:27 UTC by Zliced13

… `persist`

This allows for mp3tag to be added as a shell extension when the user installs this app.

- [ ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2022-11-25 06:28 UTC, Zliced13 commented
/verify

2022-11-28 19:59 UTC, HUMORCE requested changes
exists restrict of installation

2022-11-29 00:46 UTC, Zliced13 commented
@HUMORCE can you read my comment on the manifest when you have the time?

2022-11-29 09:12 UTC, HUMORCE commented
where is it?

2022-11-29 09:20 UTC, Zliced13 commented
Ok since GitHub will not show comments for whatever stupid reason I'll just paste it here. This is for lines 16 to 17.

@HUMORCE This part of the script will not work without administrator privileges. Should I make this optional instead?

2022-11-29 09:52 UTC, HUMORCE commented
> since GitHub will not show comments for whatever stupid reason.

you need to `submit review` after `start a review`.

> make this optional

yes

2022-12-05 18:14 UTC, Zliced13 commented
/verify

2022-12-05 18:54 UTC, HUMORCE commented
> exists restrict of installation

applies to uninstallation also.

for all operations that require admin privileges: use `notes` or `warn() | info()` instead, let users execute them manully.

e.g. some items in `scoop-checkup` need to be executed manually by the user rather than requesting admin privileges to execute when installing Scoop.

> Scoop installs programs from the command line with a minimal amount of friction.
> 
> src: https://github.com/ScoopInstaller/Scoop#what-does-scoop-do

2022-12-08 04:26 UTC, HUMORCE approved these changes

2022-12-08 19:12 UTC, merged

2023-01-30 14:22 UTC, redactedscribe commented
@Zliced13 Thanks for the enhancements, but for what reason was persist limited to only a select few files? The manifest was correct to back up all of `/data/` and `/export/`, as well as `/mp3tag.cfg`. These two directories and `/mp3tag.cfg` is what Mp3tag exports as a backup when you use the File menu "Save configuration" feature. Limiting persist to only a few files within `/data/` misses some user-customised files and the same goes for omitting all of `/export/`.

There is also `/Mp3tagSettings.zip` which is automatically created after each termination of the application. If there's a good reason behind limiting persist as you have, at minimum `/Mp3tagSettings.zip` should also be persisted because this contains all of the user's settings (the three items I've mentioned).

Would it be possible that you fix this?

2023-01-30 15:31 UTC, Zliced13 commented
Someone is already fixing this in https://github.com/ScoopInstaller/Extras/pull/10167

2023-01-30 15:45 UTC, Zliced13 commented
> @Zliced13 Thanks for the enhancements, but for what reason was persist limited to only a select few files? The manifest was correct to back up all of `/data/` and `/export/`, as well as `/mp3tag.cfg`. These two directories and `/mp3tag.cfg` is what Mp3tag exports as a backup when you use the File menu "Save configuration" feature. Limiting persist to only a few files within `/data/` misses some user-customised files and the same goes for omitting all of `/export/`.
> 
> 
> 
> There is also `/Mp3tagSettings.zip` which is automatically created after each termination of the application. If there's a good reason behind limiting persist as you have, at minimum `/Mp3tagSettings.zip` should also be persisted because this contains all of the user's settings (the three items I've mentioned).
> 
> 
> 
> Would it be possible that you fix this?

If you read my previous comments, you would know why I had to use `pre_(un)install` scripts to manually copy the files instead of the using the built in `persist` property.

2023-01-30 16:08 UTC, redactedscribe commented
I see now that you are actually copying the `/export/` directory in the pre inst/uninstall lines, but I'm still confused about why you're only persisting a select number of files from within `/data/` instead of all of them.

2023-01-30 17:42 UTC, Zliced13 commented
Because not all the files in the `/data/` directly need to be copied to the persist folder.

2023-01-30 19:04 UTC, redactedscribe commented
> Because not all the files in the `/data/` directory need to be copied to the persist folder.

This is the contents of `/data/` for me:
![mp3tag-data](https://user-images.githubusercontent.com/25013746/215565166-404aacf0-ae63-4983-9cd6-7192d62e8933.png)

- If `actions` is not persisted, all user created/modified tagging actions will be lost on uninstall.
- If `sources` is not persisted, all user created/modified source scripts for fetching metadata will be lost on uninstall.
- If `genres.ini` is not persisted, all user-defined genres tags will be lost on uninstall.
- If `tools.ini` is not persisted, all user-defined external program paths and parameters will be lost on uninstall.
- `empty.mte` appears to be a template which I haven't modified, however others may have.
- `freedb.src` may also be of importance to anyone who may have edited it.

My `/data/` folder may not contain all the potential files/folders that Mp3tag can create as user data, I don't know. What I do know is that I'd not want to lose the files which you have chosen to mark as expendable via their omission from the manifest. Backing up `/data/` as a whole would avoid losing any of this user data, much of which is important.

2023-01-31 05:38 UTC, Zliced13 commented
Next PR, I will try to add that feature to mp3tag.