droidcam-obs-plugin: Add version 1.6.0
ScoopInstaller/Extras pull request #9853
Opened 2022-11-27 02:02 UTC by Zliced13

Closes  #7107

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2022-11-27 02:02 UTC, Zliced13 commented
/verify

2022-11-27 02:06 UTC, Zliced13 commented
/verify

2022-11-27 02:50 UTC, Jimimaku commented
> Alle Änderungen sehen gut aus.
> 
> Warten Sie auf die Überprüfung durch menschliche Mitarbeiter.
> 
> ### droidcam-obs-plugin
> * [x] Beschreibung
> * [x] Lizenz
> * [x]  Hashes
> * [x] Schachbrett
> * [x] Automatische Aktualisierung

2022-11-27 02:51 UTC, Jimimaku commented
> Closes #7107
> 
> * [x]  I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2022-11-27 10:48 UTC, HUMORCE commented
for plugins of other apps: `<app>-plugin-<plugin_name>.json`

```
❯ scoop search obs
Results from local buckets...

Name             Version      Source   Binaries
----             -------      ------   --------
obs-studio-small 21.1.2       extras
obs-studio       28.1.2       extras
streamlabs-obs   1.12.1       extras
obs-studio-pre   29.0.0-beta1 versions
obs-studio27     27.2.4       versions
```

consider the variant versions of OBS, `obs-plugin-droidcam` is acceptable.

here is an example:
```
❯ scoop search keepass
Results from local buckets...

Name                               Version Source   Binaries
----                               ------- ------   --------
keepass-plugin-keeagent            0.13.3  extras
keepass-plugin-keeanywhere         2.0.3   extras
keepass-plugin-keepasshttp         1.8.4.2 extras
keepass-plugin-keepassnatmsg       2.0.14  extras
keepass-plugin-keepassrpc          1.14.0  extras
keepass-plugin-keetraytotp         0.108.0 extras
keepass-plugin-kpenhentryview      2.4.3   extras
keepass-plugin-readable-passphrase 1.3.0   extras
keepass-plugin-sequencer           0.1.1   extras
keepass-plugin-webautotype         6.8.2   extras
keepass-plugin-yafd                1.2.5.0 extras
keepass                            2.52    extras
keepassxc                          2.7.4   extras
keepassxc2.6.6                     2.6.6   versions
```

2022-11-27 17:55 UTC, Zliced13 commented
/verify

2022-11-27 22:52 UTC, Zliced13 commented
/verify

2022-11-27 22:56 UTC, HUMORCE requested changes

2022-11-27 22:56 UTC, HUMORCE commented on bucket/obs-plugin-droidcam.json
> +        "elseif (!(Test-Path \"$(appdir obs-studio $global)\")) {error \"$app requires 'obs-studio' to be installed\"; break}"
we should use `depends`, even if does not consider other variant versions. but we are considering them now, so just drop this line.

2022-11-27 23:45 UTC, HUMORCE requested changes

2022-11-27 23:45 UTC, HUMORCE commented on bucket/obs-plugin-droidcam.json
> +    "architecture": {
```suggestion
    "license": "GPL-2.0",
    "suggest": {
        "OBS": "obs-studio"
    },
    "architecture": {
```

2022-11-27 23:45 UTC, HUMORCE commented on bucket/obs-plugin-droidcam.json
> +    ],
```suggestion
    "pre_install": [
        "Remove-Item \"$dir\\data\\obs-plugins\\droidcam-obs\\`$_13_\" -Recurse",
        "'obs-studio', 'obs-studio-small', 'obs-studio27', 'obs-studio-pre' | ForEach-Object {",
        "    $obs = \"$(appdir $_ $global)\"",
        "    if (Test-Path $obs) {",
        "        info \"Install for $_\"",
        "        Copy-Item \"$dir\\data\" \"$obs\\current\" -Recurse -ErrorAction SilentlyContinue",
        "        Copy-Item \"$dir\\obs-plugins\" \"$obs\\current\" -Recurse -ErrorAction SilentlyContinue",
        "    }",
        "}"
    ],
```

2022-11-27 23:45 UTC, HUMORCE commented on bucket/obs-plugin-droidcam.json
> +    ],
```suggestion
    "pre_uninstall": [
        "'obs-studio', 'obs-studio-small', 'obs-studio27', 'obs-studio-pre' | ForEach-Object {",
        "    $obs = \"$(appdir $_ $global)\"",
        "    if (Test-Path $obs) {",
        "        info \"Uninstall for $_\"",
        "        Remove-Item \"$obs\\current\\data\\droidcam-obs\" -Force -Recurse -ErrorAction SilentlyContinue",
        "        Remove-Item \"$obs\\current\\obs-plugins\\64bit\\droidcam-obs.*\" -Force -ErrorAction SilentlyContinue",
        "    }",
        "}"
    ],
```

2022-11-28 00:27 UTC, Zliced13 commented
@HUMORCE It's important to keep the `else` function, or it will not work properly.

2022-11-28 01:10 UTC, Zliced13 commented
@HUMORCE don't merge, I am still running some tests of the manifest on my machine. I will let you know when this PR is ready.

2022-11-28 02:03 UTC, Zliced13 commented
The current manifest is not functioning properly. Why does **Scoop** only execute the first command in the `if` statement and skips the other commands? It then executes the `elseif` statement for some stupid reason, which causes a install failure.
![(VSCodium)n5J8M4_11-27-2022](https://user-images.githubusercontent.com/101912712/204175500-79bef1a8-7390-4c3e-aac0-db836492b08a.jpg)

```
> scoop install obs-plugin-droidcam                                                                   18:31:53
Installing 'obs-plugin-droidcam' (1.6.0) [64bit] from MyScoop bucket
Loading DroidCamOBS.Setup.1.6.0.exe from cache.
Checking hash of DroidCamOBS.Setup.1.6.0.exe ... ok.
Extracting dl.7z ... done.
Running pre_install script...
INFO  Install for obs-studio Copy-Item
ERROR obs-plugin-droidcam requires any obs-studio variant to be installed!
Please install either,
extras/obs-studio
extras/obs-studio-small
versions/obs-studio27
versions/obs-studio-pre
```

![(WindowsTerminal)G436C0_11-27-2022](https://user-images.githubusercontent.com/101912712/204176032-df254c40-fe58-4d9d-a7ce-ddf3fa1f1403.jpg)

2022-11-28 02:18 UTC, HUMORCE commented
this plugin is not a development tool or one of development toolchain, we should not use method such as `depends` to restrict installation.

expected behaviour: decompress file and nothing happens, if OBS not found.

2022-11-28 02:20 UTC, Zliced13 commented
> this plugin is not a development tool or one of development toolchain, we should not use method such as `depends` to restrict installation.
> 
> expected behaviour: decompress file and nothing happens, if OBS not found.

I'm not using the `depends` property in my manifest.

2022-11-28 02:22 UTC, Zliced13 commented
/verify

2022-11-28 02:48 UTC, HUMORCE requested changes

2022-11-28 02:48 UTC, HUMORCE commented on bucket/obs-plugin-droidcam.json
> +    ],
```suggestion
    "pre_install": [
        "Remove-Item \"$dir\\data\\obs-plugins\\droidcam-obs\\`$_13_\" -Recurse",
        "'obs-studio', 'obs-studio-small', 'obs-studio27', 'obs-studio-pre' | ForEach-Object {",
        "    $obs = \"$(appdir $_ $global)\"",
        "    if (Test-Path $obs) {",
        "       info \"Install for $_\"",
        "       Copy-Item \"$dir\\data\" \"$obs\\current\" -Recurse -ErrorAction SilentlyContinue",
        "       Copy-Item \"$dir\\obs-plugins\" \"$obs\\current\" -Recurse -ErrorAction SilentlyContinue",
        "   }",
        "}"
    ],
```

2022-11-28 02:48 UTC, HUMORCE commented on bucket/obs-plugin-droidcam.json
> +    ],
styles L25-26 (L35-36)
shortens L28-29 (there are no compatibility issues with windows powershell 5)

2022-11-28 02:52 UTC, HUMORCE approved these changes

2022-11-28 03:15 UTC, merged